/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Get a presigned URL for file upload
 */
export const GetPresignedUrlBody = zod.object({
  "fileName": zod.string().optional(),
  "contentType": zod.string().optional(),
  "fileSize": zod.number().optional(),
  "type": zod.enum(['AVATAR']).optional()
})

export const GetPresignedUrlResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "url": zod.string().optional(),
  "expiresInSeconds": zod.number().optional()
}).optional()
})

/**
 * @summary Confirm file upload
 */
export const ConfirmUploadBody = zod.object({
  "storageKey": zod.string().optional()
})

export const ConfirmUploadResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

