/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiResponsePresignedUrlResult,
  ApiResponseVoid,
  ConfirmUploadCommand,
  ErrorResponse,
  UploadPresignedUrlCommand
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get a presigned URL for file upload
 */
export const getPresignedUrl = (
    uploadPresignedUrlCommand: BodyType<UploadPresignedUrlCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePresignedUrlResult>(
      {url: `/api/v1/upload/presigned-url`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadPresignedUrlCommand, signal
    },
      options);
    }
  


export const getGetPresignedUrlMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrl>>, TError,{data: BodyType<UploadPresignedUrlCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrl>>, TError,{data: BodyType<UploadPresignedUrlCommand>}, TContext> => {

const mutationKey = ['getPresignedUrl'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getPresignedUrl>>, {data: BodyType<UploadPresignedUrlCommand>}> = (props) => {
          const {data} = props ?? {};

          return  getPresignedUrl(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetPresignedUrlMutationResult = NonNullable<Awaited<ReturnType<typeof getPresignedUrl>>>
    export type GetPresignedUrlMutationBody = BodyType<UploadPresignedUrlCommand>
    export type GetPresignedUrlMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Get a presigned URL for file upload
 */
export const useGetPresignedUrl = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrl>>, TError,{data: BodyType<UploadPresignedUrlCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getPresignedUrl>>,
        TError,
        {data: BodyType<UploadPresignedUrlCommand>},
        TContext
      > => {
      return useMutation(getGetPresignedUrlMutationOptions(options), queryClient);
    }
    /**
 * @summary Confirm file upload
 */
export const confirmUpload = (
    confirmUploadCommand: BodyType<ConfirmUploadCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/api/v1/upload/confirm-upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: confirmUploadCommand, signal
    },
      options);
    }
  


export const getConfirmUploadMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmUpload>>, TError,{data: BodyType<ConfirmUploadCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmUpload>>, TError,{data: BodyType<ConfirmUploadCommand>}, TContext> => {

const mutationKey = ['confirmUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmUpload>>, {data: BodyType<ConfirmUploadCommand>}> = (props) => {
          const {data} = props ?? {};

          return  confirmUpload(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmUploadMutationResult = NonNullable<Awaited<ReturnType<typeof confirmUpload>>>
    export type ConfirmUploadMutationBody = BodyType<ConfirmUploadCommand>
    export type ConfirmUploadMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Confirm file upload
 */
export const useConfirmUpload = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmUpload>>, TError,{data: BodyType<ConfirmUploadCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmUpload>>,
        TError,
        {data: BodyType<ConfirmUploadCommand>},
        TContext
      > => {
      return useMutation(getConfirmUploadMutationOptions(options), queryClient);
    }
    