/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponseVehicleSummaryProjection,
  ApiResponseVehicleResult,
  ApiResponseVoid,
  ErrorResponse,
  GetAllVehiclesParams,
  VehicleRequest
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Vehicle by ID
 */
export const getVehicleById = (
    id: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVehicleResult>(
      {url: `/api/v1/admin/vehicles/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetVehicleByIdQueryKey = (id: string,) => {
    return [
    `/api/v1/admin/vehicles/${id}`
    ] as const;
    }

    
export const getGetVehicleByIdQueryOptions = <TData = Awaited<ReturnType<typeof getVehicleById>>, TError = ErrorType<ErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVehicleById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVehicleByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVehicleById>>> = ({ signal }) => getVehicleById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVehicleById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVehicleByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getVehicleById>>>
export type GetVehicleByIdQueryError = ErrorType<ErrorResponse>


export function useGetVehicleById<TData = Awaited<ReturnType<typeof getVehicleById>>, TError = ErrorType<ErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVehicleById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVehicleById>>,
          TError,
          Awaited<ReturnType<typeof getVehicleById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVehicleById<TData = Awaited<ReturnType<typeof getVehicleById>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVehicleById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVehicleById>>,
          TError,
          Awaited<ReturnType<typeof getVehicleById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVehicleById<TData = Awaited<ReturnType<typeof getVehicleById>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVehicleById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Vehicle by ID
 */

export function useGetVehicleById<TData = Awaited<ReturnType<typeof getVehicleById>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVehicleById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVehicleByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update an existing Vehicle
 */
export const updateVehicle = (
    id: string,
    vehicleRequest: BodyType<VehicleRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVehicleResult>(
      {url: `/api/v1/admin/vehicles/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: vehicleRequest, signal
    },
      options);
    }
  


export const getUpdateVehicleMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVehicle>>, TError,{id: string;data: BodyType<VehicleRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateVehicle>>, TError,{id: string;data: BodyType<VehicleRequest>}, TContext> => {

const mutationKey = ['updateVehicle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateVehicle>>, {id: string;data: BodyType<VehicleRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateVehicle(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateVehicleMutationResult = NonNullable<Awaited<ReturnType<typeof updateVehicle>>>
    export type UpdateVehicleMutationBody = BodyType<VehicleRequest>
    export type UpdateVehicleMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update an existing Vehicle
 */
export const useUpdateVehicle = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVehicle>>, TError,{id: string;data: BodyType<VehicleRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateVehicle>>,
        TError,
        {id: string;data: BodyType<VehicleRequest>},
        TContext
      > => {
      return useMutation(getUpdateVehicleMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete an existing Vehicle
 */
export const deleteVehicle = (
    id: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/api/v1/admin/vehicles/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteVehicleMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVehicle>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteVehicle>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteVehicle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVehicle>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteVehicle(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteVehicleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVehicle>>>
    
    export type DeleteVehicleMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete an existing Vehicle
 */
export const useDeleteVehicle = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVehicle>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVehicle>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteVehicleMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all Vehicles with pagination and filtering
 */
export const getAllVehicles = (
    params?: GetAllVehiclesParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseVehicleSummaryProjection>(
      {url: `/api/v1/admin/vehicles`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllVehiclesQueryKey = (params?: GetAllVehiclesParams,) => {
    return [
    `/api/v1/admin/vehicles`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllVehiclesQueryOptions = <TData = Awaited<ReturnType<typeof getAllVehicles>>, TError = ErrorType<ErrorResponse>>(params?: GetAllVehiclesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVehicles>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllVehiclesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllVehicles>>> = ({ signal }) => getAllVehicles(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllVehicles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllVehiclesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllVehicles>>>
export type GetAllVehiclesQueryError = ErrorType<ErrorResponse>


export function useGetAllVehicles<TData = Awaited<ReturnType<typeof getAllVehicles>>, TError = ErrorType<ErrorResponse>>(
 params: undefined |  GetAllVehiclesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVehicles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVehicles>>,
          TError,
          Awaited<ReturnType<typeof getAllVehicles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllVehicles<TData = Awaited<ReturnType<typeof getAllVehicles>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllVehiclesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVehicles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVehicles>>,
          TError,
          Awaited<ReturnType<typeof getAllVehicles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllVehicles<TData = Awaited<ReturnType<typeof getAllVehicles>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllVehiclesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVehicles>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all Vehicles with pagination and filtering
 */

export function useGetAllVehicles<TData = Awaited<ReturnType<typeof getAllVehicles>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllVehiclesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVehicles>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllVehiclesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new Vehicle
 */
export const createVehicle = (
    vehicleRequest: BodyType<VehicleRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVehicleResult>(
      {url: `/api/v1/admin/vehicles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: vehicleRequest, signal
    },
      options);
    }
  


export const getCreateVehicleMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVehicle>>, TError,{data: BodyType<VehicleRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createVehicle>>, TError,{data: BodyType<VehicleRequest>}, TContext> => {

const mutationKey = ['createVehicle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createVehicle>>, {data: BodyType<VehicleRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createVehicle(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateVehicleMutationResult = NonNullable<Awaited<ReturnType<typeof createVehicle>>>
    export type CreateVehicleMutationBody = BodyType<VehicleRequest>
    export type CreateVehicleMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create a new Vehicle
 */
export const useCreateVehicle = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVehicle>>, TError,{data: BodyType<VehicleRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createVehicle>>,
        TError,
        {data: BodyType<VehicleRequest>},
        TContext
      > => {
      return useMutation(getCreateVehicleMutationOptions(options), queryClient);
    }
    