/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Get Vehicle by ID
 */
export const GetVehicleByIdParams = zod.object({
  "id": zod.string()
})

export const GetVehicleByIdResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "licensePlate": zod.string().optional(),
  "type": zod.enum(['MOTORBIKE', 'VAN', 'TRUCK']).optional(),
  "maxWeight": zod.number().optional(),
  "maxVolume": zod.number().optional(),
  "shipperId": zod.object({
  "value": zod.string().optional()
}).optional()
}).optional()
})

/**
 * @summary Update an existing Vehicle
 */
export const UpdateVehicleParams = zod.object({
  "id": zod.string()
})

export const UpdateVehicleBody = zod.object({
  "licensePlate": zod.string().optional(),
  "type": zod.enum(['MOTORBIKE', 'VAN', 'TRUCK']).optional(),
  "maxWeight": zod.number().optional(),
  "maxVolume": zod.number().optional(),
  "shipperId": zod.string().optional()
})

export const UpdateVehicleResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "licensePlate": zod.string().optional(),
  "type": zod.enum(['MOTORBIKE', 'VAN', 'TRUCK']).optional(),
  "maxWeight": zod.number().optional(),
  "maxVolume": zod.number().optional(),
  "shipperId": zod.object({
  "value": zod.string().optional()
}).optional()
}).optional()
})

/**
 * @summary Delete an existing Vehicle
 */
export const DeleteVehicleParams = zod.object({
  "id": zod.string()
})

export const DeleteVehicleResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

/**
 * @summary Get all Vehicles with pagination and filtering
 */
export const GetAllVehiclesQueryParams = zod.object({
  "filter": zod.string().optional(),
  "sorts": zod.array(zod.string()).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional()
})

export const GetAllVehiclesResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "content": zod.array(zod.object({
  "id": zod.string().optional(),
  "type": zod.string().optional(),
  "licensePlate": zod.string().optional(),
  "maxWeight": zod.number().optional(),
  "maxVolume": zod.number().optional(),
  "shipperId": zod.string().optional()
})).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional(),
  "totalElements": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "last": zod.boolean().optional(),
  "first": zod.boolean().optional()
}).optional()
})

/**
 * @summary Create a new Vehicle
 */
export const CreateVehicleBody = zod.object({
  "licensePlate": zod.string().optional(),
  "type": zod.enum(['MOTORBIKE', 'VAN', 'TRUCK']).optional(),
  "maxWeight": zod.number().optional(),
  "maxVolume": zod.number().optional(),
  "shipperId": zod.string().optional()
})

export const CreateVehicleResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "licensePlate": zod.string().optional(),
  "type": zod.enum(['MOTORBIKE', 'VAN', 'TRUCK']).optional(),
  "maxWeight": zod.number().optional(),
  "maxVolume": zod.number().optional(),
  "shipperId": zod.object({
  "value": zod.string().optional()
}).optional()
}).optional()
})

