/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Verify Code
 */
export const VerifyCodeBody = zod.object({
  "purpose": zod.enum(['PHONE_VERIFICATION', 'EMAIL_VERIFICATION', 'FORGOT_PASSWORD']).optional(),
  "recipient": zod.string().optional(),
  "code": zod.string().optional()
})

export const VerifyCodeResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "token": zod.string().optional(),
  "expiresIn": zod.number().optional()
}).optional()
})

/**
 * @summary Send Verification Code
 */
export const SendVerificationBody = zod.object({
  "purpose": zod.enum(['PHONE_VERIFICATION', 'EMAIL_VERIFICATION', 'FORGOT_PASSWORD']).optional(),
  "channel": zod.enum(['EMAIL', 'PHONE']).optional(),
  "recipient": zod.string().optional()
})

export const SendVerificationResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

/**
 * @summary Rotate Token
 */



export const RotateTokenBody = zod.object({
  "refreshToken": zod.string().min(1)
})

export const RotateTokenResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "accessToken": zod.string().optional(),
  "refreshToken": zod.string().optional(),
  "expiresIn": zod.number().optional(),
  "tokenType": zod.string().optional()
}).optional()
})

/**
 * @summary Reset Password
 */
export const ResetPasswordBody = zod.object({
  "verificationToken": zod.string().optional(),
  "newPassword": zod.string().optional()
})

export const ResetPasswordResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

/**
 * @summary Register User
 */
export const RegisterUserBody = zod.object({
  "verificationToken": zod.string().optional(),
  "email": zod.string().optional(),
  "fullName": zod.string().optional(),
  "password": zod.string().optional()
})

export const RegisterUserResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "fullName": zod.string().optional(),
  "email": zod.string().optional(),
  "phoneNumber": zod.string().optional(),
  "emailVerified": zod.boolean().optional(),
  "phoneVerified": zod.boolean().optional()
}).optional()
})

/**
 * @summary Logout User
 */



export const LogoutUserBody = zod.object({
  "refreshToken": zod.string().min(1)
})

export const LogoutUserResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

/**
 * @summary User Login
 */
export const LoginBody = zod.object({
  "credentialId": zod.string().optional(),
  "password": zod.string().optional()
})

export const LoginResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "accessToken": zod.string().optional(),
  "refreshToken": zod.string().optional(),
  "expiresIn": zod.number().optional(),
  "tokenType": zod.string().optional()
}).optional()
})

