/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Verify Code
 */
export const VerifyCodeBody = zod.object({
  "purpose": zod.enum(['PHONE_VERIFICATION', 'EMAIL_VERIFICATION', 'FORGOT_PASSWORD']).optional(),
  "recipient": zod.string().optional(),
  "code": zod.string().optional()
})

/**
 * @summary Send Verification Code
 */
export const SendVerificationBody = zod.object({
  "purpose": zod.enum(['PHONE_VERIFICATION', 'EMAIL_VERIFICATION', 'FORGOT_PASSWORD']).optional(),
  "channel": zod.enum(['EMAIL', 'PHONE']).optional(),
  "recipient": zod.string().optional()
})

/**
 * @summary Rotate Token
 */
export const RotateTokenBody = zod.object({
  "refreshToken": zod.string().optional()
})

/**
 * @summary Reset Password
 */
export const ResetPasswordBody = zod.object({
  "verificationToken": zod.string().optional(),
  "newPassword": zod.string().optional()
})

/**
 * @summary Register User
 */
export const RegisterUserBody = zod.object({
  "verificationToken": zod.string().optional(),
  "email": zod.string().optional(),
  "fullName": zod.string().optional(),
  "password": zod.string().optional()
})

/**
 * @summary Logout User
 */
export const LogoutUserBody = zod.object({
  "refreshToken": zod.string().optional()
})

/**
 * @summary User Login
 */
export const LoginBody = zod.object({
  "credentialId": zod.string().optional(),
  "password": zod.string().optional()
})

