/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Top Up Wallet
 */
export const topUpBodyAmountMin = 10000;



export const TopUpBody = zod.object({
  "amount": zod.number().min(topUpBodyAmountMin),
  "provider": zod.enum(['SYSTEM', 'VNPAY', 'MOMO', 'BANK'])
})

export const TopUpResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.string().optional()
})

/**
 * @summary Get My Wallet
 */
export const GetMyWalletResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "walletId": zod.string().optional(),
  "balance": zod.number().optional(),
  "currency": zod.string().optional(),
  "formattedBalance": zod.string().optional(),
  "status": zod.enum(['ACTIVE', 'LOCKED', 'FROZEN']).optional()
}).optional()
})

