/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseContactResult,
  ApiResponsePageResponseContactResult,
  ApiResponseVoid,
  CreateContactRequest,
  ErrorResponse,
  GetMyContactsParams,
  LookupContactParams,
  UpdateContactRequest
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Update an existing contact
 */
export const updateContact = (
    contactId: string,
    updateContactRequest: BodyType<UpdateContactRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseContactResult>(
      {url: `/api/v1/contacts/${contactId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateContactRequest, signal
    },
      options);
    }
  


export const getUpdateContactMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContact>>, TError,{contactId: string;data: BodyType<UpdateContactRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateContact>>, TError,{contactId: string;data: BodyType<UpdateContactRequest>}, TContext> => {

const mutationKey = ['updateContact'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateContact>>, {contactId: string;data: BodyType<UpdateContactRequest>}> = (props) => {
          const {contactId,data} = props ?? {};

          return  updateContact(contactId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateContactMutationResult = NonNullable<Awaited<ReturnType<typeof updateContact>>>
    export type UpdateContactMutationBody = BodyType<UpdateContactRequest>
    export type UpdateContactMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update an existing contact
 */
export const useUpdateContact = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContact>>, TError,{contactId: string;data: BodyType<UpdateContactRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateContact>>,
        TError,
        {contactId: string;data: BodyType<UpdateContactRequest>},
        TContext
      > => {
      return useMutation(getUpdateContactMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a contact from address book
 */
export const deleteContact = (
    contactId: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/api/v1/contacts/${contactId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteContactMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,{contactId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,{contactId: string}, TContext> => {

const mutationKey = ['deleteContact'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContact>>, {contactId: string}> = (props) => {
          const {contactId} = props ?? {};

          return  deleteContact(contactId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteContactMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContact>>>
    
    export type DeleteContactMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete a contact from address book
 */
export const useDeleteContact = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,{contactId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteContact>>,
        TError,
        {contactId: string},
        TContext
      > => {
      return useMutation(getDeleteContactMutationOptions(options), queryClient);
    }
    /**
 * @summary Get my address book
 */
export const getMyContacts = (
    params?: GetMyContactsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseContactResult>(
      {url: `/api/v1/contacts`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetMyContactsQueryKey = (params?: GetMyContactsParams,) => {
    return [
    `/api/v1/contacts`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMyContactsQueryOptions = <TData = Awaited<ReturnType<typeof getMyContacts>>, TError = ErrorType<ErrorResponse>>(params?: GetMyContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyContacts>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyContactsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyContacts>>> = ({ signal }) => getMyContacts(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyContacts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyContactsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyContacts>>>
export type GetMyContactsQueryError = ErrorType<ErrorResponse>


export function useGetMyContacts<TData = Awaited<ReturnType<typeof getMyContacts>>, TError = ErrorType<ErrorResponse>>(
 params: undefined |  GetMyContactsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyContacts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyContacts>>,
          TError,
          Awaited<ReturnType<typeof getMyContacts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyContacts<TData = Awaited<ReturnType<typeof getMyContacts>>, TError = ErrorType<ErrorResponse>>(
 params?: GetMyContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyContacts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyContacts>>,
          TError,
          Awaited<ReturnType<typeof getMyContacts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyContacts<TData = Awaited<ReturnType<typeof getMyContacts>>, TError = ErrorType<ErrorResponse>>(
 params?: GetMyContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyContacts>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get my address book
 */

export function useGetMyContacts<TData = Awaited<ReturnType<typeof getMyContacts>>, TError = ErrorType<ErrorResponse>>(
 params?: GetMyContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyContacts>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyContactsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Add a new contact to address book
 */
export const createContact = (
    createContactRequest: BodyType<CreateContactRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseContactResult>(
      {url: `/api/v1/contacts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createContactRequest, signal
    },
      options);
    }
  


export const getCreateContactMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContact>>, TError,{data: BodyType<CreateContactRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createContact>>, TError,{data: BodyType<CreateContactRequest>}, TContext> => {

const mutationKey = ['createContact'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createContact>>, {data: BodyType<CreateContactRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createContact(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateContactMutationResult = NonNullable<Awaited<ReturnType<typeof createContact>>>
    export type CreateContactMutationBody = BodyType<CreateContactRequest>
    export type CreateContactMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Add a new contact to address book
 */
export const useCreateContact = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContact>>, TError,{data: BodyType<CreateContactRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createContact>>,
        TError,
        {data: BodyType<CreateContactRequest>},
        TContext
      > => {
      return useMutation(getCreateContactMutationOptions(options), queryClient);
    }
    /**
 * @summary Auto-fill lookup by phone number
 */
export const lookupContact = (
    params: LookupContactParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseContactResult>(
      {url: `/api/v1/contacts/lookup`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getLookupContactQueryKey = (params?: LookupContactParams,) => {
    return [
    `/api/v1/contacts/lookup`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getLookupContactQueryOptions = <TData = Awaited<ReturnType<typeof lookupContact>>, TError = ErrorType<ErrorResponse>>(params: LookupContactParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lookupContact>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLookupContactQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof lookupContact>>> = ({ signal }) => lookupContact(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof lookupContact>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LookupContactQueryResult = NonNullable<Awaited<ReturnType<typeof lookupContact>>>
export type LookupContactQueryError = ErrorType<ErrorResponse>


export function useLookupContact<TData = Awaited<ReturnType<typeof lookupContact>>, TError = ErrorType<ErrorResponse>>(
 params: LookupContactParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof lookupContact>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lookupContact>>,
          TError,
          Awaited<ReturnType<typeof lookupContact>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLookupContact<TData = Awaited<ReturnType<typeof lookupContact>>, TError = ErrorType<ErrorResponse>>(
 params: LookupContactParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lookupContact>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lookupContact>>,
          TError,
          Awaited<ReturnType<typeof lookupContact>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLookupContact<TData = Awaited<ReturnType<typeof lookupContact>>, TError = ErrorType<ErrorResponse>>(
 params: LookupContactParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lookupContact>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Auto-fill lookup by phone number
 */

export function useLookupContact<TData = Awaited<ReturnType<typeof lookupContact>>, TError = ErrorType<ErrorResponse>>(
 params: LookupContactParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lookupContact>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLookupContactQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




