/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Update an existing contact
 */
export const UpdateContactParams = zod.object({
  "contactId": zod.string()
})

export const UpdateContactBody = zod.object({
  "name": zod.string().optional(),
  "phoneNumber": zod.string().optional(),
  "address": zod.string().optional(),
  "note": zod.string().optional()
})

export const UpdateContactResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "name": zod.string().optional(),
  "phoneNumber": zod.string().optional(),
  "address": zod.string().optional(),
  "note": zod.string().optional()
}).optional()
})

/**
 * @summary Delete a contact from address book
 */
export const DeleteContactParams = zod.object({
  "contactId": zod.string()
})

export const DeleteContactResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

/**
 * @summary Get my address book
 */
export const GetMyContactsQueryParams = zod.object({
  "filter": zod.string().optional(),
  "sorts": zod.array(zod.string()).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional()
})

export const GetMyContactsResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "content": zod.array(zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "name": zod.string().optional(),
  "phoneNumber": zod.string().optional(),
  "address": zod.string().optional(),
  "note": zod.string().optional()
})).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional(),
  "totalElements": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "last": zod.boolean().optional(),
  "first": zod.boolean().optional()
}).optional()
})

/**
 * @summary Add a new contact to address book
 */
export const CreateContactBody = zod.object({
  "name": zod.string().optional(),
  "phoneNumber": zod.string().optional(),
  "address": zod.string().optional(),
  "note": zod.string().optional()
})

export const CreateContactResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "name": zod.string().optional(),
  "phoneNumber": zod.string().optional(),
  "address": zod.string().optional(),
  "note": zod.string().optional()
}).optional()
})

/**
 * @summary Auto-fill lookup by phone number
 */
export const LookupContactQueryParams = zod.object({
  "phone": zod.string()
})

export const LookupContactResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "name": zod.string().optional(),
  "phoneNumber": zod.string().optional(),
  "address": zod.string().optional(),
  "note": zod.string().optional()
}).optional()
})

