/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponseProvinceSummaryProjection,
  ApiResponseProvinceResult,
  ApiResponseVoid,
  CreateProvinceCommand,
  ErrorResponse,
  GetAllProvincesParams,
  UpdateProvinceRequest
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Lấy thông tin chi tiết của một tỉnh/thành phố theo ID
 * @summary Get a Province by ID
 */
export const getProvinceById = (
    id: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseProvinceResult>(
      {url: `/api/v1/admin/provinces/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetProvinceByIdQueryKey = (id: string,) => {
    return [
    `/api/v1/admin/provinces/${id}`
    ] as const;
    }

    
export const getGetProvinceByIdQueryOptions = <TData = Awaited<ReturnType<typeof getProvinceById>>, TError = ErrorType<ErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProvinceById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProvinceByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProvinceById>>> = ({ signal }) => getProvinceById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProvinceById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProvinceByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProvinceById>>>
export type GetProvinceByIdQueryError = ErrorType<ErrorResponse>


export function useGetProvinceById<TData = Awaited<ReturnType<typeof getProvinceById>>, TError = ErrorType<ErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProvinceById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProvinceById>>,
          TError,
          Awaited<ReturnType<typeof getProvinceById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProvinceById<TData = Awaited<ReturnType<typeof getProvinceById>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProvinceById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProvinceById>>,
          TError,
          Awaited<ReturnType<typeof getProvinceById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProvinceById<TData = Awaited<ReturnType<typeof getProvinceById>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProvinceById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a Province by ID
 */

export function useGetProvinceById<TData = Awaited<ReturnType<typeof getProvinceById>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProvinceById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProvinceByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update an existing Province (Cấp Tỉnh)
 */
export const updateProvince = (
    id: string,
    updateProvinceRequest: BodyType<UpdateProvinceRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseProvinceResult>(
      {url: `/api/v1/admin/provinces/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateProvinceRequest, signal
    },
      options);
    }
  


export const getUpdateProvinceMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProvince>>, TError,{id: string;data: BodyType<UpdateProvinceRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProvince>>, TError,{id: string;data: BodyType<UpdateProvinceRequest>}, TContext> => {

const mutationKey = ['updateProvince'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProvince>>, {id: string;data: BodyType<UpdateProvinceRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProvince(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProvinceMutationResult = NonNullable<Awaited<ReturnType<typeof updateProvince>>>
    export type UpdateProvinceMutationBody = BodyType<UpdateProvinceRequest>
    export type UpdateProvinceMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update an existing Province (Cấp Tỉnh)
 */
export const useUpdateProvince = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProvince>>, TError,{id: string;data: BodyType<UpdateProvinceRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProvince>>,
        TError,
        {id: string;data: BodyType<UpdateProvinceRequest>},
        TContext
      > => {
      return useMutation(getUpdateProvinceMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete an existing Province (Cấp Tỉnh)
 */
export const deleteProvince = (
    id: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/api/v1/admin/provinces/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteProvinceMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProvince>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProvince>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteProvince'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProvince>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteProvince(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProvinceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProvince>>>
    
    export type DeleteProvinceMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete an existing Province (Cấp Tỉnh)
 */
export const useDeleteProvince = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProvince>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProvince>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteProvinceMutationOptions(options), queryClient);
    }
    /**
 * Hỗ trợ phân trang, sắp xếp và filter RSQL. Ví dụ: code==HCM;name==*Hồ*
 * @summary Get list of Provinces with pagination and filtering
 */
export const getAllProvinces = (
    params?: GetAllProvincesParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseProvinceSummaryProjection>(
      {url: `/api/v1/admin/provinces`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllProvincesQueryKey = (params?: GetAllProvincesParams,) => {
    return [
    `/api/v1/admin/provinces`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllProvincesQueryOptions = <TData = Awaited<ReturnType<typeof getAllProvinces>>, TError = ErrorType<ErrorResponse>>(params?: GetAllProvincesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProvinces>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllProvincesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProvinces>>> = ({ signal }) => getAllProvinces(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllProvinces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllProvincesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllProvinces>>>
export type GetAllProvincesQueryError = ErrorType<ErrorResponse>


export function useGetAllProvinces<TData = Awaited<ReturnType<typeof getAllProvinces>>, TError = ErrorType<ErrorResponse>>(
 params: undefined |  GetAllProvincesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProvinces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProvinces>>,
          TError,
          Awaited<ReturnType<typeof getAllProvinces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProvinces<TData = Awaited<ReturnType<typeof getAllProvinces>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllProvincesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProvinces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProvinces>>,
          TError,
          Awaited<ReturnType<typeof getAllProvinces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProvinces<TData = Awaited<ReturnType<typeof getAllProvinces>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllProvincesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProvinces>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get list of Provinces with pagination and filtering
 */

export function useGetAllProvinces<TData = Awaited<ReturnType<typeof getAllProvinces>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllProvincesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProvinces>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllProvincesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new Province (Cấp Tỉnh)
 */
export const createProvince = (
    createProvinceCommand: BodyType<CreateProvinceCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseProvinceResult>(
      {url: `/api/v1/admin/provinces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProvinceCommand, signal
    },
      options);
    }
  


export const getCreateProvinceMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProvince>>, TError,{data: BodyType<CreateProvinceCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createProvince>>, TError,{data: BodyType<CreateProvinceCommand>}, TContext> => {

const mutationKey = ['createProvince'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProvince>>, {data: BodyType<CreateProvinceCommand>}> = (props) => {
          const {data} = props ?? {};

          return  createProvince(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProvinceMutationResult = NonNullable<Awaited<ReturnType<typeof createProvince>>>
    export type CreateProvinceMutationBody = BodyType<CreateProvinceCommand>
    export type CreateProvinceMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create a new Province (Cấp Tỉnh)
 */
export const useCreateProvince = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProvince>>, TError,{data: BodyType<CreateProvinceCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProvince>>,
        TError,
        {data: BodyType<CreateProvinceCommand>},
        TContext
      > => {
      return useMutation(getCreateProvinceMutationOptions(options), queryClient);
    }
    