/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Update an existing Province (Cấp Tỉnh)
 */
export const UpdateProvinceParams = zod.object({
  "id": zod.string()
})

export const UpdateProvinceBody = zod.object({
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "type": zod.enum(['CITY', 'PROVINCE']).optional()
})

export const UpdateProvinceResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "type": zod.enum(['CITY', 'PROVINCE']).optional()
}).optional()
})

/**
 * @summary Delete an existing Province (Cấp Tỉnh)
 */
export const DeleteProvinceParams = zod.object({
  "id": zod.string()
})

export const DeleteProvinceResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

/**
 * Hỗ trợ phân trang, sắp xếp và filter RSQL. Ví dụ: code==HCM;name==*Hồ*
 * @summary Get list of Provinces with pagination and filtering
 */
export const GetAllProvincesQueryParams = zod.object({
  "filter": zod.string().optional(),
  "sorts": zod.array(zod.string()).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional()
})

export const GetAllProvincesResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "content": zod.array(zod.object({
  "name": zod.string().optional(),
  "id": zod.string().optional(),
  "type": zod.string().optional(),
  "code": zod.string().optional()
})).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional(),
  "totalElements": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "last": zod.boolean().optional(),
  "first": zod.boolean().optional()
}).optional()
})

/**
 * @summary Create a new Province (Cấp Tỉnh)
 */
export const CreateProvinceBody = zod.object({
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "type": zod.enum(['CITY', 'PROVINCE']).optional()
})

export const CreateProvinceResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "type": zod.enum(['CITY', 'PROVINCE']).optional()
}).optional()
})

