/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Get Depot by ID
 */
export const GetDepotByIdParams = zod.object({
  "depotId": zod.string()
})

export const GetDepotByIdResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "name": zod.string().optional(),
  "type": zod.enum(['BGD', 'SOC']).optional(),
  "lat": zod.number().optional(),
  "lng": zod.number().optional(),
  "isStartNode": zod.boolean().optional()
}).optional()
})

/**
 * @summary Update an existing Depot
 */
export const UpdateDepotParams = zod.object({
  "depotId": zod.string()
})

export const UpdateDepotBody = zod.object({
  "name": zod.string().optional(),
  "type": zod.enum(['BGD', 'SOC']).optional(),
  "latitude": zod.number().optional(),
  "longitude": zod.number().optional()
})

export const UpdateDepotResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "name": zod.string().optional(),
  "type": zod.enum(['BGD', 'SOC']).optional(),
  "lat": zod.number().optional(),
  "lng": zod.number().optional(),
  "isStartNode": zod.boolean().optional()
}).optional()
})

/**
 * @summary Delete a Depot
 */
export const DeleteDepotParams = zod.object({
  "depotId": zod.string()
})

export const DeleteDepotResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

/**
 * @summary Get all Depots with pagination and filtering
 */
export const GetAllDepotsQueryParams = zod.object({
  "filter": zod.string().optional(),
  "sorts": zod.array(zod.string()).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional()
})

export const GetAllDepotsResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "content": zod.array(zod.object({
  "name": zod.string().optional(),
  "id": zod.string().optional(),
  "type": zod.enum(['BGD', 'SOC']).optional(),
  "lat": zod.number().optional(),
  "lng": zod.number().optional(),
  "startNode": zod.boolean().optional()
})).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional(),
  "totalElements": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "last": zod.boolean().optional(),
  "first": zod.boolean().optional()
}).optional()
})

/**
 * @summary Create a new Depot
 */
export const CreateDepotBody = zod.object({
  "name": zod.string().optional(),
  "type": zod.enum(['BGD', 'SOC']).optional(),
  "lat": zod.number().optional(),
  "lng": zod.number().optional()
})

export const CreateDepotResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "name": zod.string().optional(),
  "type": zod.enum(['BGD', 'SOC']).optional(),
  "lat": zod.number().optional(),
  "lng": zod.number().optional(),
  "isStartNode": zod.boolean().optional()
}).optional()
})

