/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseDepotResult,
  ApiResponsePageResponseDepotSummaryProjection,
  ApiResponseVoid,
  CreateDepotCommand,
  ErrorResponse,
  GetAllDepotsParams,
  UpdateDepotRequest
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Depot by ID
 */
export const getDepotById = (
    depotId: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseDepotResult>(
      {url: `/api/v1/admin/depots/${depotId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDepotByIdQueryKey = (depotId: string,) => {
    return [
    `/api/v1/admin/depots/${depotId}`
    ] as const;
    }

    
export const getGetDepotByIdQueryOptions = <TData = Awaited<ReturnType<typeof getDepotById>>, TError = ErrorType<ErrorResponse>>(depotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepotById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDepotByIdQueryKey(depotId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDepotById>>> = ({ signal }) => getDepotById(depotId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(depotId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDepotById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDepotByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getDepotById>>>
export type GetDepotByIdQueryError = ErrorType<ErrorResponse>


export function useGetDepotById<TData = Awaited<ReturnType<typeof getDepotById>>, TError = ErrorType<ErrorResponse>>(
 depotId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepotById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepotById>>,
          TError,
          Awaited<ReturnType<typeof getDepotById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepotById<TData = Awaited<ReturnType<typeof getDepotById>>, TError = ErrorType<ErrorResponse>>(
 depotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepotById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepotById>>,
          TError,
          Awaited<ReturnType<typeof getDepotById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepotById<TData = Awaited<ReturnType<typeof getDepotById>>, TError = ErrorType<ErrorResponse>>(
 depotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepotById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Depot by ID
 */

export function useGetDepotById<TData = Awaited<ReturnType<typeof getDepotById>>, TError = ErrorType<ErrorResponse>>(
 depotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepotById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDepotByIdQueryOptions(depotId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update an existing Depot
 */
export const updateDepot = (
    depotId: string,
    updateDepotRequest: BodyType<UpdateDepotRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseDepotResult>(
      {url: `/api/v1/admin/depots/${depotId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateDepotRequest, signal
    },
      options);
    }
  


export const getUpdateDepotMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDepot>>, TError,{depotId: string;data: BodyType<UpdateDepotRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDepot>>, TError,{depotId: string;data: BodyType<UpdateDepotRequest>}, TContext> => {

const mutationKey = ['updateDepot'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDepot>>, {depotId: string;data: BodyType<UpdateDepotRequest>}> = (props) => {
          const {depotId,data} = props ?? {};

          return  updateDepot(depotId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDepotMutationResult = NonNullable<Awaited<ReturnType<typeof updateDepot>>>
    export type UpdateDepotMutationBody = BodyType<UpdateDepotRequest>
    export type UpdateDepotMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update an existing Depot
 */
export const useUpdateDepot = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDepot>>, TError,{depotId: string;data: BodyType<UpdateDepotRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDepot>>,
        TError,
        {depotId: string;data: BodyType<UpdateDepotRequest>},
        TContext
      > => {
      return useMutation(getUpdateDepotMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a Depot
 */
export const deleteDepot = (
    depotId: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/api/v1/admin/depots/${depotId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteDepotMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDepot>>, TError,{depotId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDepot>>, TError,{depotId: string}, TContext> => {

const mutationKey = ['deleteDepot'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDepot>>, {depotId: string}> = (props) => {
          const {depotId} = props ?? {};

          return  deleteDepot(depotId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDepotMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDepot>>>
    
    export type DeleteDepotMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete a Depot
 */
export const useDeleteDepot = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDepot>>, TError,{depotId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDepot>>,
        TError,
        {depotId: string},
        TContext
      > => {
      return useMutation(getDeleteDepotMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all Depots with pagination and filtering
 */
export const getAllDepots = (
    params?: GetAllDepotsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseDepotSummaryProjection>(
      {url: `/api/v1/admin/depots`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllDepotsQueryKey = (params?: GetAllDepotsParams,) => {
    return [
    `/api/v1/admin/depots`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllDepotsQueryOptions = <TData = Awaited<ReturnType<typeof getAllDepots>>, TError = ErrorType<ErrorResponse>>(params?: GetAllDepotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllDepots>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllDepotsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllDepots>>> = ({ signal }) => getAllDepots(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllDepots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllDepotsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllDepots>>>
export type GetAllDepotsQueryError = ErrorType<ErrorResponse>


export function useGetAllDepots<TData = Awaited<ReturnType<typeof getAllDepots>>, TError = ErrorType<ErrorResponse>>(
 params: undefined |  GetAllDepotsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllDepots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllDepots>>,
          TError,
          Awaited<ReturnType<typeof getAllDepots>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllDepots<TData = Awaited<ReturnType<typeof getAllDepots>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllDepotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllDepots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllDepots>>,
          TError,
          Awaited<ReturnType<typeof getAllDepots>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllDepots<TData = Awaited<ReturnType<typeof getAllDepots>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllDepotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllDepots>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all Depots with pagination and filtering
 */

export function useGetAllDepots<TData = Awaited<ReturnType<typeof getAllDepots>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllDepotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllDepots>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllDepotsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new Depot
 */
export const createDepot = (
    createDepotCommand: BodyType<CreateDepotCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseDepotResult>(
      {url: `/api/v1/admin/depots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDepotCommand, signal
    },
      options);
    }
  


export const getCreateDepotMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDepot>>, TError,{data: BodyType<CreateDepotCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createDepot>>, TError,{data: BodyType<CreateDepotCommand>}, TContext> => {

const mutationKey = ['createDepot'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDepot>>, {data: BodyType<CreateDepotCommand>}> = (props) => {
          const {data} = props ?? {};

          return  createDepot(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDepotMutationResult = NonNullable<Awaited<ReturnType<typeof createDepot>>>
    export type CreateDepotMutationBody = BodyType<CreateDepotCommand>
    export type CreateDepotMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create a new Depot
 */
export const useCreateDepot = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDepot>>, TError,{data: BodyType<CreateDepotCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDepot>>,
        TError,
        {data: BodyType<CreateDepotCommand>},
        TContext
      > => {
      return useMutation(getCreateDepotMutationOptions(options), queryClient);
    }
    