/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * Hỗ trợ phân trang, sắp xếp và filter RSQL. Ví dụ: status==PENDING;type==EXPRESS
 * @summary Get list of Orders with pagination and filtering
 */
export const GetAllOrdersQueryParams = zod.object({
  "filter": zod.string().optional(),
  "sorts": zod.array(zod.string()).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional()
})

export const GetAllOrdersResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "content": zod.array(zod.object({
  "id": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "trackingCode": zod.string().optional(),
  "customerId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "totalAmount": zod.number().optional(),
  "createdAt": zod.string().optional()
})).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional(),
  "totalElements": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "last": zod.boolean().optional(),
  "first": zod.boolean().optional()
}).optional()
})

/**
 * @summary Create a new Order
 */
export const CreateOrderBody = zod.object({
  "trackingCode": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "customerId": zod.string().optional(),
  "senderId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "senderPhone": zod.string().optional(),
  "senderAddress": zod.string().optional(),
  "senderWardId": zod.string().optional(),
  "senderProvinceId": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientPhone": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "recipientWardId": zod.string().optional(),
  "recipientProvinceId": zod.string().optional(),
  "description": zod.string().optional(),
  "weight": zod.number().optional(),
  "dimLength": zod.number().optional(),
  "dimWidth": zod.number().optional(),
  "dimHeight": zod.number().optional(),
  "valueDeclared": zod.number().optional(),
  "fragile": zod.boolean().optional(),
  "requiresSignature": zod.boolean().optional(),
  "shippingFee": zod.number().optional(),
  "insuranceFee": zod.number().optional()
})

export const CreateOrderResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "trackingCode": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "customerId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "totalAmount": zod.number().optional(),
  "assignedDriverId": zod.string().optional()
}).optional()
})

/**
 * @summary Start Order Delivery
 */
export const StartDeliveryParams = zod.object({
  "orderId": zod.string()
})

export const StartDeliveryResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "trackingCode": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "customerId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "totalAmount": zod.number().optional(),
  "assignedDriverId": zod.string().optional()
}).optional()
})

/**
 * @summary Reject Order
 */
export const RejectOrderParams = zod.object({
  "orderId": zod.string()
})

export const RejectOrderBody = zod.object({
  "rejectionReason": zod.string().optional()
})

export const RejectOrderResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "trackingCode": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "customerId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "totalAmount": zod.number().optional(),
  "assignedDriverId": zod.string().optional()
}).optional()
})

/**
 * @summary Update Recipient Information
 */
export const UpdateRecipientParams = zod.object({
  "orderId": zod.string()
})

export const UpdateRecipientBody = zod.object({
  "recipientName": zod.string().optional(),
  "recipientPhone": zod.string().optional(),
  "recipientAddress": zod.string().optional()
})

export const UpdateRecipientResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "trackingCode": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "customerId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "totalAmount": zod.number().optional(),
  "assignedDriverId": zod.string().optional()
}).optional()
})

/**
 * @summary Deliver Order
 */
export const DeliverOrderParams = zod.object({
  "orderId": zod.string()
})

export const DeliverOrderBody = zod.object({
  "deliveryDate": zod.string().optional()
})

export const DeliverOrderResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "trackingCode": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "customerId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "totalAmount": zod.number().optional(),
  "assignedDriverId": zod.string().optional()
}).optional()
})

/**
 * @summary Confirm Order
 */
export const ConfirmOrderParams = zod.object({
  "orderId": zod.string()
})

export const ConfirmOrderResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "trackingCode": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "customerId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "totalAmount": zod.number().optional(),
  "assignedDriverId": zod.string().optional()
}).optional()
})

/**
 * @summary Cancel Order
 */
export const CancelOrderParams = zod.object({
  "orderId": zod.string()
})

export const CancelOrderResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "trackingCode": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "customerId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "totalAmount": zod.number().optional(),
  "assignedDriverId": zod.string().optional()
}).optional()
})

/**
 * @summary Assign Driver to Order
 */
export const AssignDriverParams = zod.object({
  "orderId": zod.string()
})

export const AssignDriverBody = zod.object({
  "driverId": zod.string().optional(),
  "depotId": zod.string().optional()
})

export const AssignDriverResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "trackingCode": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "customerId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "totalAmount": zod.number().optional(),
  "assignedDriverId": zod.string().optional()
}).optional()
})

/**
 * @summary Get Order by ID
 */
export const GetOrderByIdParams = zod.object({
  "orderId": zod.string()
})

export const GetOrderByIdResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "dimensions": zod.string().optional(),
  "description": zod.string().optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "trackingCode": zod.string().optional(),
  "customerId": zod.string().optional(),
  "senderId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "senderPhone": zod.string().optional(),
  "senderAddress": zod.string().optional(),
  "senderWardId": zod.string().optional(),
  "senderProvinceId": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientPhone": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "recipientWardId": zod.string().optional(),
  "recipientProvinceId": zod.string().optional(),
  "weight": zod.number().optional(),
  "valueDeclared": zod.number().optional(),
  "fragile": zod.boolean().optional(),
  "requiresSignature": zod.boolean().optional(),
  "shippingFee": zod.number().optional(),
  "insuranceFee": zod.number().optional(),
  "totalAmount": zod.number().optional(),
  "assignedDriverId": zod.string().optional(),
  "depotId": zod.string().optional(),
  "estimatedDeliveryDate": zod.string().optional(),
  "actualDeliveryDate": zod.string().optional(),
  "notes": zod.string().optional(),
  "rejectionReason": zod.string().optional(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional()
}).optional()
})

/**
 * @summary Delete Order
 */
export const DeleteOrderParams = zod.object({
  "orderId": zod.string()
})

export const DeleteOrderResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

/**
 * @summary Get Order by Tracking Code
 */
export const GetOrderByTrackingCodeParams = zod.object({
  "trackingCode": zod.string()
})

export const GetOrderByTrackingCodeResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "type": zod.enum(['EXPRESS', 'STANDARD', 'ECONOMY']).optional(),
  "dimensions": zod.string().optional(),
  "description": zod.string().optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'CANCELLED']).optional(),
  "trackingCode": zod.string().optional(),
  "customerId": zod.string().optional(),
  "senderId": zod.string().optional(),
  "senderName": zod.string().optional(),
  "senderPhone": zod.string().optional(),
  "senderAddress": zod.string().optional(),
  "senderWardId": zod.string().optional(),
  "senderProvinceId": zod.string().optional(),
  "recipientName": zod.string().optional(),
  "recipientPhone": zod.string().optional(),
  "recipientAddress": zod.string().optional(),
  "recipientWardId": zod.string().optional(),
  "recipientProvinceId": zod.string().optional(),
  "weight": zod.number().optional(),
  "valueDeclared": zod.number().optional(),
  "fragile": zod.boolean().optional(),
  "requiresSignature": zod.boolean().optional(),
  "shippingFee": zod.number().optional(),
  "insuranceFee": zod.number().optional(),
  "totalAmount": zod.number().optional(),
  "assignedDriverId": zod.string().optional(),
  "depotId": zod.string().optional(),
  "estimatedDeliveryDate": zod.string().optional(),
  "actualDeliveryDate": zod.string().optional(),
  "notes": zod.string().optional(),
  "rejectionReason": zod.string().optional(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional()
}).optional()
})

