/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOrderDetailProjection,
  ApiResponseOrderResult,
  ApiResponsePageResponseOrderSummaryProjection,
  ApiResponseVoid,
  AssignDriverRequest,
  CreateOrderCommand,
  DeliverOrderRequest,
  ErrorResponse,
  GetAllOrdersParams,
  RejectOrderRequest,
  UpdateRecipientRequest
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Hỗ trợ phân trang, sắp xếp và filter RSQL. Ví dụ: status==PENDING;type==EXPRESS
 * @summary Get list of Orders with pagination and filtering
 */
export const getAllOrders = (
    params?: GetAllOrdersParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseOrderSummaryProjection>(
      {url: `/api/v1/orders`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllOrdersQueryKey = (params?: GetAllOrdersParams,) => {
    return [
    `/api/v1/orders`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getAllOrders>>, TError = ErrorType<ErrorResponse>>(params?: GetAllOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllOrders>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllOrdersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllOrders>>> = ({ signal }) => getAllOrders(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllOrders>>>
export type GetAllOrdersQueryError = ErrorType<ErrorResponse>


export function useGetAllOrders<TData = Awaited<ReturnType<typeof getAllOrders>>, TError = ErrorType<ErrorResponse>>(
 params: undefined |  GetAllOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllOrders>>,
          TError,
          Awaited<ReturnType<typeof getAllOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllOrders<TData = Awaited<ReturnType<typeof getAllOrders>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllOrders>>,
          TError,
          Awaited<ReturnType<typeof getAllOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllOrders<TData = Awaited<ReturnType<typeof getAllOrders>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllOrders>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get list of Orders with pagination and filtering
 */

export function useGetAllOrders<TData = Awaited<ReturnType<typeof getAllOrders>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllOrders>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new Order
 */
export const createOrder = (
    createOrderCommand: BodyType<CreateOrderCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseOrderResult>(
      {url: `/api/v1/orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOrderCommand, signal
    },
      options);
    }
  


export const getCreateOrderMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: BodyType<CreateOrderCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: BodyType<CreateOrderCommand>}, TContext> => {

const mutationKey = ['createOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrder>>, {data: BodyType<CreateOrderCommand>}> = (props) => {
          const {data} = props ?? {};

          return  createOrder(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrderMutationResult = NonNullable<Awaited<ReturnType<typeof createOrder>>>
    export type CreateOrderMutationBody = BodyType<CreateOrderCommand>
    export type CreateOrderMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create a new Order
 */
export const useCreateOrder = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: BodyType<CreateOrderCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOrder>>,
        TError,
        {data: BodyType<CreateOrderCommand>},
        TContext
      > => {
      return useMutation(getCreateOrderMutationOptions(options), queryClient);
    }
    /**
 * @summary Start Order Delivery
 */
export const startDelivery = (
    orderId: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseOrderResult>(
      {url: `/api/v1/orders/${orderId}/start-delivery`, method: 'PATCH', signal
    },
      options);
    }
  


export const getStartDeliveryMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startDelivery>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof startDelivery>>, TError,{orderId: string}, TContext> => {

const mutationKey = ['startDelivery'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startDelivery>>, {orderId: string}> = (props) => {
          const {orderId} = props ?? {};

          return  startDelivery(orderId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartDeliveryMutationResult = NonNullable<Awaited<ReturnType<typeof startDelivery>>>
    
    export type StartDeliveryMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Start Order Delivery
 */
export const useStartDelivery = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startDelivery>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startDelivery>>,
        TError,
        {orderId: string},
        TContext
      > => {
      return useMutation(getStartDeliveryMutationOptions(options), queryClient);
    }
    /**
 * @summary Reject Order
 */
export const rejectOrder = (
    orderId: string,
    rejectOrderRequest: BodyType<RejectOrderRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseOrderResult>(
      {url: `/api/v1/orders/${orderId}/reject`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: rejectOrderRequest, signal
    },
      options);
    }
  


export const getRejectOrderMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectOrder>>, TError,{orderId: string;data: BodyType<RejectOrderRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof rejectOrder>>, TError,{orderId: string;data: BodyType<RejectOrderRequest>}, TContext> => {

const mutationKey = ['rejectOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectOrder>>, {orderId: string;data: BodyType<RejectOrderRequest>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  rejectOrder(orderId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RejectOrderMutationResult = NonNullable<Awaited<ReturnType<typeof rejectOrder>>>
    export type RejectOrderMutationBody = BodyType<RejectOrderRequest>
    export type RejectOrderMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Reject Order
 */
export const useRejectOrder = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectOrder>>, TError,{orderId: string;data: BodyType<RejectOrderRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectOrder>>,
        TError,
        {orderId: string;data: BodyType<RejectOrderRequest>},
        TContext
      > => {
      return useMutation(getRejectOrderMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Recipient Information
 */
export const updateRecipient = (
    orderId: string,
    updateRecipientRequest: BodyType<UpdateRecipientRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseOrderResult>(
      {url: `/api/v1/orders/${orderId}/recipient`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateRecipientRequest, signal
    },
      options);
    }
  


export const getUpdateRecipientMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipient>>, TError,{orderId: string;data: BodyType<UpdateRecipientRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateRecipient>>, TError,{orderId: string;data: BodyType<UpdateRecipientRequest>}, TContext> => {

const mutationKey = ['updateRecipient'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRecipient>>, {orderId: string;data: BodyType<UpdateRecipientRequest>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  updateRecipient(orderId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRecipientMutationResult = NonNullable<Awaited<ReturnType<typeof updateRecipient>>>
    export type UpdateRecipientMutationBody = BodyType<UpdateRecipientRequest>
    export type UpdateRecipientMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update Recipient Information
 */
export const useUpdateRecipient = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRecipient>>, TError,{orderId: string;data: BodyType<UpdateRecipientRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRecipient>>,
        TError,
        {orderId: string;data: BodyType<UpdateRecipientRequest>},
        TContext
      > => {
      return useMutation(getUpdateRecipientMutationOptions(options), queryClient);
    }
    /**
 * @summary Deliver Order
 */
export const deliverOrder = (
    orderId: string,
    deliverOrderRequest: BodyType<DeliverOrderRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseOrderResult>(
      {url: `/api/v1/orders/${orderId}/deliver`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: deliverOrderRequest, signal
    },
      options);
    }
  


export const getDeliverOrderMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deliverOrder>>, TError,{orderId: string;data: BodyType<DeliverOrderRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deliverOrder>>, TError,{orderId: string;data: BodyType<DeliverOrderRequest>}, TContext> => {

const mutationKey = ['deliverOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deliverOrder>>, {orderId: string;data: BodyType<DeliverOrderRequest>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  deliverOrder(orderId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeliverOrderMutationResult = NonNullable<Awaited<ReturnType<typeof deliverOrder>>>
    export type DeliverOrderMutationBody = BodyType<DeliverOrderRequest>
    export type DeliverOrderMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Deliver Order
 */
export const useDeliverOrder = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deliverOrder>>, TError,{orderId: string;data: BodyType<DeliverOrderRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deliverOrder>>,
        TError,
        {orderId: string;data: BodyType<DeliverOrderRequest>},
        TContext
      > => {
      return useMutation(getDeliverOrderMutationOptions(options), queryClient);
    }
    /**
 * @summary Confirm Order
 */
export const confirmOrder = (
    orderId: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseOrderResult>(
      {url: `/api/v1/orders/${orderId}/confirm`, method: 'PATCH', signal
    },
      options);
    }
  


export const getConfirmOrderMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmOrder>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmOrder>>, TError,{orderId: string}, TContext> => {

const mutationKey = ['confirmOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmOrder>>, {orderId: string}> = (props) => {
          const {orderId} = props ?? {};

          return  confirmOrder(orderId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmOrderMutationResult = NonNullable<Awaited<ReturnType<typeof confirmOrder>>>
    
    export type ConfirmOrderMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Confirm Order
 */
export const useConfirmOrder = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmOrder>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmOrder>>,
        TError,
        {orderId: string},
        TContext
      > => {
      return useMutation(getConfirmOrderMutationOptions(options), queryClient);
    }
    /**
 * @summary Cancel Order
 */
export const cancelOrder = (
    orderId: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseOrderResult>(
      {url: `/api/v1/orders/${orderId}/cancel`, method: 'PATCH', signal
    },
      options);
    }
  


export const getCancelOrderMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelOrder>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelOrder>>, TError,{orderId: string}, TContext> => {

const mutationKey = ['cancelOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelOrder>>, {orderId: string}> = (props) => {
          const {orderId} = props ?? {};

          return  cancelOrder(orderId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CancelOrderMutationResult = NonNullable<Awaited<ReturnType<typeof cancelOrder>>>
    
    export type CancelOrderMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Cancel Order
 */
export const useCancelOrder = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelOrder>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelOrder>>,
        TError,
        {orderId: string},
        TContext
      > => {
      return useMutation(getCancelOrderMutationOptions(options), queryClient);
    }
    /**
 * @summary Assign Driver to Order
 */
export const assignDriver = (
    orderId: string,
    assignDriverRequest: BodyType<AssignDriverRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseOrderResult>(
      {url: `/api/v1/orders/${orderId}/assign`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: assignDriverRequest, signal
    },
      options);
    }
  


export const getAssignDriverMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignDriver>>, TError,{orderId: string;data: BodyType<AssignDriverRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof assignDriver>>, TError,{orderId: string;data: BodyType<AssignDriverRequest>}, TContext> => {

const mutationKey = ['assignDriver'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignDriver>>, {orderId: string;data: BodyType<AssignDriverRequest>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  assignDriver(orderId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AssignDriverMutationResult = NonNullable<Awaited<ReturnType<typeof assignDriver>>>
    export type AssignDriverMutationBody = BodyType<AssignDriverRequest>
    export type AssignDriverMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Assign Driver to Order
 */
export const useAssignDriver = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignDriver>>, TError,{orderId: string;data: BodyType<AssignDriverRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignDriver>>,
        TError,
        {orderId: string;data: BodyType<AssignDriverRequest>},
        TContext
      > => {
      return useMutation(getAssignDriverMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Order by ID
 */
export const getOrderById = (
    orderId: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseOrderDetailProjection>(
      {url: `/api/v1/orders/${orderId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOrderByIdQueryKey = (orderId: string,) => {
    return [
    `/api/v1/orders/${orderId}`
    ] as const;
    }

    
export const getGetOrderByIdQueryOptions = <TData = Awaited<ReturnType<typeof getOrderById>>, TError = ErrorType<ErrorResponse>>(orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrderByIdQueryKey(orderId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrderById>>> = ({ signal }) => getOrderById(orderId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orderId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrderByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrderById>>>
export type GetOrderByIdQueryError = ErrorType<ErrorResponse>


export function useGetOrderById<TData = Awaited<ReturnType<typeof getOrderById>>, TError = ErrorType<ErrorResponse>>(
 orderId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrderById>>,
          TError,
          Awaited<ReturnType<typeof getOrderById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrderById<TData = Awaited<ReturnType<typeof getOrderById>>, TError = ErrorType<ErrorResponse>>(
 orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrderById>>,
          TError,
          Awaited<ReturnType<typeof getOrderById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrderById<TData = Awaited<ReturnType<typeof getOrderById>>, TError = ErrorType<ErrorResponse>>(
 orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Order by ID
 */

export function useGetOrderById<TData = Awaited<ReturnType<typeof getOrderById>>, TError = ErrorType<ErrorResponse>>(
 orderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrderByIdQueryOptions(orderId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Delete Order
 */
export const deleteOrder = (
    orderId: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/api/v1/orders/${orderId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteOrderMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrder>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrder>>, TError,{orderId: string}, TContext> => {

const mutationKey = ['deleteOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrder>>, {orderId: string}> = (props) => {
          const {orderId} = props ?? {};

          return  deleteOrder(orderId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrderMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrder>>>
    
    export type DeleteOrderMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete Order
 */
export const useDeleteOrder = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrder>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrder>>,
        TError,
        {orderId: string},
        TContext
      > => {
      return useMutation(getDeleteOrderMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Order by Tracking Code
 */
export const getOrderByTrackingCode = (
    trackingCode: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseOrderDetailProjection>(
      {url: `/api/v1/orders/tracking/${trackingCode}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOrderByTrackingCodeQueryKey = (trackingCode: string,) => {
    return [
    `/api/v1/orders/tracking/${trackingCode}`
    ] as const;
    }

    
export const getGetOrderByTrackingCodeQueryOptions = <TData = Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError = ErrorType<ErrorResponse>>(trackingCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrderByTrackingCodeQueryKey(trackingCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrderByTrackingCode>>> = ({ signal }) => getOrderByTrackingCode(trackingCode, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(trackingCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrderByTrackingCodeQueryResult = NonNullable<Awaited<ReturnType<typeof getOrderByTrackingCode>>>
export type GetOrderByTrackingCodeQueryError = ErrorType<ErrorResponse>


export function useGetOrderByTrackingCode<TData = Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError = ErrorType<ErrorResponse>>(
 trackingCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrderByTrackingCode>>,
          TError,
          Awaited<ReturnType<typeof getOrderByTrackingCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrderByTrackingCode<TData = Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError = ErrorType<ErrorResponse>>(
 trackingCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrderByTrackingCode>>,
          TError,
          Awaited<ReturnType<typeof getOrderByTrackingCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrderByTrackingCode<TData = Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError = ErrorType<ErrorResponse>>(
 trackingCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Order by Tracking Code
 */

export function useGetOrderByTrackingCode<TData = Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError = ErrorType<ErrorResponse>>(
 trackingCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderByTrackingCode>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrderByTrackingCodeQueryOptions(trackingCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




