/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseDebugOtpResult,
  ApiResponseVoid,
  DebugOtpParams,
  ErrorResponse,
  SyncPermissionCommand
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const syncPermissions = (
    syncPermissionCommand: BodyType<SyncPermissionCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/api/v1/internal/permissions/sync`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: syncPermissionCommand, signal
    },
      options);
    }
  


export const getSyncPermissionsMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPermissions>>, TError,{data: BodyType<SyncPermissionCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof syncPermissions>>, TError,{data: BodyType<SyncPermissionCommand>}, TContext> => {

const mutationKey = ['syncPermissions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncPermissions>>, {data: BodyType<SyncPermissionCommand>}> = (props) => {
          const {data} = props ?? {};

          return  syncPermissions(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SyncPermissionsMutationResult = NonNullable<Awaited<ReturnType<typeof syncPermissions>>>
    export type SyncPermissionsMutationBody = BodyType<SyncPermissionCommand>
    export type SyncPermissionsMutationError = ErrorType<ErrorResponse>

    export const useSyncPermissions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPermissions>>, TError,{data: BodyType<SyncPermissionCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncPermissions>>,
        TError,
        {data: BodyType<SyncPermissionCommand>},
        TContext
      > => {
      return useMutation(getSyncPermissionsMutationOptions(options), queryClient);
    }
    export const debugOtp = (
    params: DebugOtpParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseDebugOtpResult>(
      {url: `/api/v1/internal/debug-otp`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getDebugOtpQueryKey = (params?: DebugOtpParams,) => {
    return [
    `/api/v1/internal/debug-otp`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getDebugOtpQueryOptions = <TData = Awaited<ReturnType<typeof debugOtp>>, TError = ErrorType<ErrorResponse>>(params: DebugOtpParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof debugOtp>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDebugOtpQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof debugOtp>>> = ({ signal }) => debugOtp(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof debugOtp>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DebugOtpQueryResult = NonNullable<Awaited<ReturnType<typeof debugOtp>>>
export type DebugOtpQueryError = ErrorType<ErrorResponse>


export function useDebugOtp<TData = Awaited<ReturnType<typeof debugOtp>>, TError = ErrorType<ErrorResponse>>(
 params: DebugOtpParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof debugOtp>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof debugOtp>>,
          TError,
          Awaited<ReturnType<typeof debugOtp>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDebugOtp<TData = Awaited<ReturnType<typeof debugOtp>>, TError = ErrorType<ErrorResponse>>(
 params: DebugOtpParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof debugOtp>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof debugOtp>>,
          TError,
          Awaited<ReturnType<typeof debugOtp>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDebugOtp<TData = Awaited<ReturnType<typeof debugOtp>>, TError = ErrorType<ErrorResponse>>(
 params: DebugOtpParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof debugOtp>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDebugOtp<TData = Awaited<ReturnType<typeof debugOtp>>, TError = ErrorType<ErrorResponse>>(
 params: DebugOtpParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof debugOtp>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDebugOtpQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




