/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const SyncPermissionsBody = zod.object({
  "packageName": zod.string().optional()
})

export const DebugOtpQueryParams = zod.object({
  "phoneNumber": zod.string()
})

