/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseCompleteSetupMfaResult,
  ApiResponseListMfaMethodProjection,
  ApiResponseLoginResult,
  ApiResponseMapStringString,
  ApiResponseMfaChallengeResult,
  ApiResponseVoid,
  CompleteSetupMfaCommand,
  ErrorResponse,
  InitiateMfaSetupParams,
  MfaChallengeCommand,
  RecoveryMfaCommand,
  VerifyMfaCommand
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const verifyMfa = (
    verifyMfaCommand: BodyType<VerifyMfaCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseLoginResult>(
      {url: `/api/v1/auth/mfa/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyMfaCommand, signal
    },
      options);
    }
  


export const getVerifyMfaMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyMfa>>, TError,{data: BodyType<VerifyMfaCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyMfa>>, TError,{data: BodyType<VerifyMfaCommand>}, TContext> => {

const mutationKey = ['verifyMfa'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyMfa>>, {data: BodyType<VerifyMfaCommand>}> = (props) => {
          const {data} = props ?? {};

          return  verifyMfa(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyMfaMutationResult = NonNullable<Awaited<ReturnType<typeof verifyMfa>>>
    export type VerifyMfaMutationBody = BodyType<VerifyMfaCommand>
    export type VerifyMfaMutationError = ErrorType<ErrorResponse>

    export const useVerifyMfa = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyMfa>>, TError,{data: BodyType<VerifyMfaCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyMfa>>,
        TError,
        {data: BodyType<VerifyMfaCommand>},
        TContext
      > => {
      return useMutation(getVerifyMfaMutationOptions(options), queryClient);
    }
    /**
 * @summary Khởi tạo quá trình thiết lập MFA cho người dùng
 */
export const initiateMfaSetup = (
    params: InitiateMfaSetupParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseMapStringString>(
      {url: `/api/v1/auth/mfa/setup/init`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getInitiateMfaSetupMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initiateMfaSetup>>, TError,{params: InitiateMfaSetupParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof initiateMfaSetup>>, TError,{params: InitiateMfaSetupParams}, TContext> => {

const mutationKey = ['initiateMfaSetup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof initiateMfaSetup>>, {params: InitiateMfaSetupParams}> = (props) => {
          const {params} = props ?? {};

          return  initiateMfaSetup(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type InitiateMfaSetupMutationResult = NonNullable<Awaited<ReturnType<typeof initiateMfaSetup>>>
    
    export type InitiateMfaSetupMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Khởi tạo quá trình thiết lập MFA cho người dùng
 */
export const useInitiateMfaSetup = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initiateMfaSetup>>, TError,{params: InitiateMfaSetupParams}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof initiateMfaSetup>>,
        TError,
        {params: InitiateMfaSetupParams},
        TContext
      > => {
      return useMutation(getInitiateMfaSetupMutationOptions(options), queryClient);
    }
    /**
 * @summary Hoàn tất quá trình thiết lập MFA cho người dùng
 */
export const completeMfaSetup = (
    completeSetupMfaCommand: BodyType<CompleteSetupMfaCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseCompleteSetupMfaResult>(
      {url: `/api/v1/auth/mfa/setup/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeSetupMfaCommand, signal
    },
      options);
    }
  


export const getCompleteMfaSetupMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeMfaSetup>>, TError,{data: BodyType<CompleteSetupMfaCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof completeMfaSetup>>, TError,{data: BodyType<CompleteSetupMfaCommand>}, TContext> => {

const mutationKey = ['completeMfaSetup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeMfaSetup>>, {data: BodyType<CompleteSetupMfaCommand>}> = (props) => {
          const {data} = props ?? {};

          return  completeMfaSetup(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteMfaSetupMutationResult = NonNullable<Awaited<ReturnType<typeof completeMfaSetup>>>
    export type CompleteMfaSetupMutationBody = BodyType<CompleteSetupMfaCommand>
    export type CompleteMfaSetupMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Hoàn tất quá trình thiết lập MFA cho người dùng
 */
export const useCompleteMfaSetup = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeMfaSetup>>, TError,{data: BodyType<CompleteSetupMfaCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeMfaSetup>>,
        TError,
        {data: BodyType<CompleteSetupMfaCommand>},
        TContext
      > => {
      return useMutation(getCompleteMfaSetupMutationOptions(options), queryClient);
    }
    export const recoverMfa = (
    recoveryMfaCommand: BodyType<RecoveryMfaCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseLoginResult>(
      {url: `/api/v1/auth/mfa/recovery`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: recoveryMfaCommand, signal
    },
      options);
    }
  


export const getRecoverMfaMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recoverMfa>>, TError,{data: BodyType<RecoveryMfaCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof recoverMfa>>, TError,{data: BodyType<RecoveryMfaCommand>}, TContext> => {

const mutationKey = ['recoverMfa'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof recoverMfa>>, {data: BodyType<RecoveryMfaCommand>}> = (props) => {
          const {data} = props ?? {};

          return  recoverMfa(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RecoverMfaMutationResult = NonNullable<Awaited<ReturnType<typeof recoverMfa>>>
    export type RecoverMfaMutationBody = BodyType<RecoveryMfaCommand>
    export type RecoverMfaMutationError = ErrorType<ErrorResponse>

    export const useRecoverMfa = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recoverMfa>>, TError,{data: BodyType<RecoveryMfaCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof recoverMfa>>,
        TError,
        {data: BodyType<RecoveryMfaCommand>},
        TContext
      > => {
      return useMutation(getRecoverMfaMutationOptions(options), queryClient);
    }
    /**
 * @summary Thực hiện MFA challenge
 */
export const challengeMfa = (
    mfaChallengeCommand: BodyType<MfaChallengeCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseMfaChallengeResult>(
      {url: `/api/v1/auth/mfa/challenge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mfaChallengeCommand, signal
    },
      options);
    }
  


export const getChallengeMfaMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof challengeMfa>>, TError,{data: BodyType<MfaChallengeCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof challengeMfa>>, TError,{data: BodyType<MfaChallengeCommand>}, TContext> => {

const mutationKey = ['challengeMfa'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof challengeMfa>>, {data: BodyType<MfaChallengeCommand>}> = (props) => {
          const {data} = props ?? {};

          return  challengeMfa(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChallengeMfaMutationResult = NonNullable<Awaited<ReturnType<typeof challengeMfa>>>
    export type ChallengeMfaMutationBody = BodyType<MfaChallengeCommand>
    export type ChallengeMfaMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Thực hiện MFA challenge
 */
export const useChallengeMfa = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof challengeMfa>>, TError,{data: BodyType<MfaChallengeCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof challengeMfa>>,
        TError,
        {data: BodyType<MfaChallengeCommand>},
        TContext
      > => {
      return useMutation(getChallengeMfaMutationOptions(options), queryClient);
    }
    export const getMfaMethods = (
    
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseListMfaMethodProjection>(
      {url: `/api/v1/auth/mfa/methods`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMfaMethodsQueryKey = () => {
    return [
    `/api/v1/auth/mfa/methods`
    ] as const;
    }

    
export const getGetMfaMethodsQueryOptions = <TData = Awaited<ReturnType<typeof getMfaMethods>>, TError = ErrorType<ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMfaMethods>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMfaMethodsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMfaMethods>>> = ({ signal }) => getMfaMethods(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMfaMethods>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMfaMethodsQueryResult = NonNullable<Awaited<ReturnType<typeof getMfaMethods>>>
export type GetMfaMethodsQueryError = ErrorType<ErrorResponse>


export function useGetMfaMethods<TData = Awaited<ReturnType<typeof getMfaMethods>>, TError = ErrorType<ErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMfaMethods>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMfaMethods>>,
          TError,
          Awaited<ReturnType<typeof getMfaMethods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMfaMethods<TData = Awaited<ReturnType<typeof getMfaMethods>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMfaMethods>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMfaMethods>>,
          TError,
          Awaited<ReturnType<typeof getMfaMethods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMfaMethods<TData = Awaited<ReturnType<typeof getMfaMethods>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMfaMethods>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMfaMethods<TData = Awaited<ReturnType<typeof getMfaMethods>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMfaMethods>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMfaMethodsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const removeMfaMethod = (
    method: 'TOTP' | 'EMAIL' | 'WEBAUTHN',
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/api/v1/auth/mfa/remove/${method}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getRemoveMfaMethodMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeMfaMethod>>, TError,{method: 'TOTP' | 'EMAIL' | 'WEBAUTHN'}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof removeMfaMethod>>, TError,{method: 'TOTP' | 'EMAIL' | 'WEBAUTHN'}, TContext> => {

const mutationKey = ['removeMfaMethod'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeMfaMethod>>, {method: 'TOTP' | 'EMAIL' | 'WEBAUTHN'}> = (props) => {
          const {method} = props ?? {};

          return  removeMfaMethod(method,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveMfaMethodMutationResult = NonNullable<Awaited<ReturnType<typeof removeMfaMethod>>>
    
    export type RemoveMfaMethodMutationError = ErrorType<ErrorResponse>

    export const useRemoveMfaMethod = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeMfaMethod>>, TError,{method: 'TOTP' | 'EMAIL' | 'WEBAUTHN'}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeMfaMethod>>,
        TError,
        {method: 'TOTP' | 'EMAIL' | 'WEBAUTHN'},
        TContext
      > => {
      return useMutation(getRemoveMfaMethodMutationOptions(options), queryClient);
    }
    