/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const VerifyMfaBody = zod.object({
  "challengeId": zod.string().optional(),
  "code": zod.string().optional()
})

export const VerifyMfaResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "accessToken": zod.string().optional(),
  "refreshToken": zod.string().optional(),
  "expiresIn": zod.number().optional(),
  "tokenType": zod.string().optional(),
  "mfaRequired": zod.boolean().optional(),
  "mfaMethods": zod.array(zod.object({
  "method": zod.string().optional()
})).optional(),
  "verificationToken": zod.string().optional()
}).optional()
})

/**
 * @summary Khởi tạo quá trình thiết lập MFA cho người dùng
 */
export const InitiateMfaSetupQueryParams = zod.object({
  "method": zod.enum(['TOTP', 'EMAIL', 'WEBAUTHN'])
})

export const InitiateMfaSetupResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.record(zod.string(), zod.string()).optional()
})

/**
 * @summary Hoàn tất quá trình thiết lập MFA cho người dùng
 */
export const CompleteMfaSetupBody = zod.object({
  "method": zod.enum(['TOTP', 'EMAIL', 'WEBAUTHN']).optional(),
  "credential": zod.string().optional(),
  "properties": zod.record(zod.string(), zod.string()).optional()
})

export const CompleteMfaSetupResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "backupCodes": zod.array(zod.string()).optional()
}).optional()
})

export const RecoverMfaBody = zod.object({
  "challengeId": zod.string().optional(),
  "code": zod.string().optional()
})

export const RecoverMfaResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "accessToken": zod.string().optional(),
  "refreshToken": zod.string().optional(),
  "expiresIn": zod.number().optional(),
  "tokenType": zod.string().optional(),
  "mfaRequired": zod.boolean().optional(),
  "mfaMethods": zod.array(zod.object({
  "method": zod.string().optional()
})).optional(),
  "verificationToken": zod.string().optional()
}).optional()
})

/**
 * @summary Thực hiện MFA challenge
 */
export const ChallengeMfaBody = zod.object({
  "method": zod.enum(['TOTP', 'EMAIL', 'WEBAUTHN']).optional(),
  "verificationToken": zod.string().optional()
})

export const ChallengeMfaResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "method": zod.enum(['TOTP', 'EMAIL', 'WEBAUTHN']).optional(),
  "challengeId": zod.string().optional(),
  "status": zod.string().optional(),
  "publicOptionsJson": zod.string().optional(),
  "maskedTarget": zod.string().optional()
}).optional()
})

export const GetMfaMethodsResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.array(zod.object({
  "method": zod.string().optional()
})).optional()
})

export const RemoveMfaMethodParams = zod.object({
  "method": zod.enum(['TOTP', 'EMAIL', 'WEBAUTHN'])
})

export const RemoveMfaMethodResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

