import {useInfiniteQuery, type QueryKey} from '@tanstack/react-query';

interface PageResponse<T> {
    content?: T[];
    last?: boolean;
    number?: number;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
    first?: boolean;
}

interface UseInfiniteScrollProps<T, TParams> {
    queryKey: QueryKey;
    // This is the function generated by Orval (e.g., getAllRoles)
    fetchFn: (params: TParams) => Promise<{ data: PageResponse<T> }>;
    params: TParams;
    size?: number;
}

export function useInfiniteScroll<T, TParams extends { page?: number; size?: number }>({
                                                                                           queryKey,
                                                                                           fetchFn,
                                                                                           params,
                                                                                           size = 10,
                                                                                       }: UseInfiniteScrollProps<T, TParams>) {
    return useInfiniteQuery({
        // Include params in the key so it refetches when search/filters change
        queryKey: [...queryKey, params],
        queryFn: ({pageParam = 0}) =>
            fetchFn({
                ...params,
                page: pageParam,
                size,
            }),
        initialPageParam: 0,
        getNextPageParam: (lastPage) => {
            const data = lastPage.data;
            return data?.last ? undefined : (data?.number ?? 0) + 1;
        },
        // Keep previous data when changing search terms to avoid jarring layout shifts
        placeholderData: (previousData) => previousData,
    });
}