/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const UpdateRoleParams = zod.object({
  "id": zod.string()
})

export const UpdateRoleBody = zod.object({
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "default": zod.boolean().optional()
})

export const UpdateRoleResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "isDefault": zod.boolean().optional(),
  "systemRole": zod.boolean().optional()
}).optional()
})

export const DeleteRoleParams = zod.object({
  "id": zod.string()
})

export const DeleteRoleResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

export const GetAllRolesQueryParams = zod.object({
  "filter": zod.string().optional(),
  "sorts": zod.array(zod.string()).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional()
})

export const GetAllRolesResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "content": zod.array(zod.object({
  "name": zod.string().optional(),
  "id": zod.string().optional(),
  "systemRole": zod.boolean().optional(),
  "getisDefault": zod.boolean().optional()
})).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional(),
  "totalElements": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "last": zod.boolean().optional(),
  "first": zod.boolean().optional()
}).optional()
})

export const CreateRoleBody = zod.object({
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "isDefault": zod.boolean().optional()
})

export const CreateRoleResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "isDefault": zod.boolean().optional(),
  "systemRole": zod.boolean().optional()
}).optional()
})

