/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


export const GetAllPermissionsQueryParams = zod.object({
  "filter": zod.string().optional(),
  "sorts": zod.array(zod.string()).optional()
})

export const GetAllPermissionsResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.record(zod.string(), zod.array(zod.object({
  "name": zod.string().optional(),
  "resource": zod.string().optional(),
  "id": zod.string().optional(),
  "description": zod.string().optional(),
  "action": zod.string().optional()
}))).optional()
})

