/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  HandleMomoWebhookBody
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const handleMomoWebhook = (
    handleMomoWebhookBody: BodyType<HandleMomoWebhookBody>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/api/v1/wallet/webhook/momo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: handleMomoWebhookBody, signal
    },
      options);
    }
  


export const getHandleMomoWebhookMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleMomoWebhook>>, TError,{data: BodyType<HandleMomoWebhookBody>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof handleMomoWebhook>>, TError,{data: BodyType<HandleMomoWebhookBody>}, TContext> => {

const mutationKey = ['handleMomoWebhook'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof handleMomoWebhook>>, {data: BodyType<HandleMomoWebhookBody>}> = (props) => {
          const {data} = props ?? {};

          return  handleMomoWebhook(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type HandleMomoWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof handleMomoWebhook>>>
    export type HandleMomoWebhookMutationBody = BodyType<HandleMomoWebhookBody>
    export type HandleMomoWebhookMutationError = ErrorType<ErrorResponse>

    export const useHandleMomoWebhook = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleMomoWebhook>>, TError,{data: BodyType<HandleMomoWebhookBody>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof handleMomoWebhook>>,
        TError,
        {data: BodyType<HandleMomoWebhookBody>},
        TContext
      > => {
      return useMutation(getHandleMomoWebhookMutationOptions(options), queryClient);
    }
    