/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseDepotSummaryProjection } from './pageResponseDepotSummaryProjection';

export interface ApiResponsePageResponseDepotSummaryProjection {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: PageResponseDepotSummaryProjection;
}
