/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseMapStringStringData } from './apiResponseMapStringStringData';

export interface ApiResponseMapStringString {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: ApiResponseMapStringStringData;
}
