/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ApiResponseVoid {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: unknown;
}
