/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponsePermissionSummaryProjection } from './pageResponsePermissionSummaryProjection';

export interface ApiResponsePageResponsePermissionSummaryProjection {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: PageResponsePermissionSummaryProjection;
}
