/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MfaMethodProjection } from './mfaMethodProjection';

export interface ApiResponseListMfaMethodProjection {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: MfaMethodProjection[];
}
