/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProvinceResult } from './provinceResult';

export interface ApiResponseProvinceResult {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: ProvinceResult;
}
