/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WalletResult } from './walletResult';

export interface ApiResponseWalletResult {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: WalletResult;
}
