/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseProvinceSummaryProjection } from './pageResponseProvinceSummaryProjection';

export interface ApiResponsePageResponseProvinceSummaryProjection {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: PageResponseProvinceSummaryProjection;
}
