/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResponseOrderSummaryProjection } from './pageResponseOrderSummaryProjection';

export interface ApiResponsePageResponseOrderSummaryProjection {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: PageResponseOrderSummaryProjection;
}
