/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CompleteSetupMfaResult } from './completeSetupMfaResult';

export interface ApiResponseCompleteSetupMfaResult {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: CompleteSetupMfaResult;
}
