/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PermissionSummaryProjection } from './permissionSummaryProjection';

export type ApiResponseMapStringListPermissionSummaryProjectionData = {[key: string]: PermissionSummaryProjection[]};
