/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DepotResult } from './depotResult';

export interface ApiResponseDepotResult {
  timestamp?: string;
  status?: number;
  message?: string;
  data?: DepotResult;
}
