/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CompleteSetupMfaCommandMethod } from './completeSetupMfaCommandMethod';
import type { CompleteSetupMfaCommandProperties } from './completeSetupMfaCommandProperties';

export interface CompleteSetupMfaCommand {
  method?: CompleteSetupMfaCommandMethod;
  credential?: string;
  properties?: CompleteSetupMfaCommandProperties;
}
