/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ContactId } from './contactId';

export interface ContactResult {
  id?: ContactId;
  name?: string;
  phoneNumber?: string;
  address?: string;
  note?: string;
}
