/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateWardCommandType = typeof CreateWardCommandType[keyof typeof CreateWardCommandType];


export const CreateWardCommandType = {
  WARD: 'WARD',
  COMMUNE: 'COMMUNE',
  TOWNSHIP: 'TOWNSHIP',
  TOWN: 'TOWN',
} as const;
