/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateDepotCommandType = typeof CreateDepotCommandType[keyof typeof CreateDepotCommandType];


export const CreateDepotCommandType = {
  BGD: 'BGD',
  SOC: 'SOC',
} as const;
