/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateOrderCommandType } from './createOrderCommandType';

export interface CreateOrderCommand {
  trackingCode?: string;
  type?: CreateOrderCommandType;
  customerId?: string;
  senderId?: string;
  senderName?: string;
  senderPhone?: string;
  senderAddress?: string;
  senderWardId?: string;
  senderProvinceId?: string;
  recipientName?: string;
  recipientPhone?: string;
  recipientAddress?: string;
  recipientWardId?: string;
  recipientProvinceId?: string;
  description?: string;
  weight?: number;
  dimLength?: number;
  dimWidth?: number;
  dimHeight?: number;
  valueDeclared?: number;
  fragile?: boolean;
  requiresSignature?: boolean;
  shippingFee?: number;
  insuranceFee?: number;
}
