/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateWardCommandType } from './createWardCommandType';
import type { Polygon } from './polygon';
import type { ProvinceId } from './provinceId';

export interface CreateWardCommand {
  code?: string;
  name?: string;
  provinceId?: ProvinceId;
  type?: CreateWardCommandType;
  polygon?: Polygon;
}
