/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateOrderCommandType = typeof CreateOrderCommandType[keyof typeof CreateOrderCommandType];


export const CreateOrderCommandType = {
  EXPRESS: 'EXPRESS',
  STANDARD: 'STANDARD',
  ECONOMY: 'ECONOMY',
} as const;
