/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateProvinceCommandType } from './createProvinceCommandType';

export interface CreateProvinceCommand {
  code?: string;
  name?: string;
  type?: CreateProvinceCommandType;
}
