/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateProvinceCommandType = typeof CreateProvinceCommandType[keyof typeof CreateProvinceCommandType];


export const CreateProvinceCommandType = {
  CITY: 'CITY',
  PROVINCE: 'PROVINCE',
} as const;
