/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateDepotCommandType } from './createDepotCommandType';

export interface CreateDepotCommand {
  name?: string;
  type?: CreateDepotCommandType;
  lat?: number;
  lng?: number;
}
