/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DepotSummaryProjectionType } from './depotSummaryProjectionType';

export interface DepotSummaryProjection {
  name?: string;
  id?: string;
  type?: DepotSummaryProjectionType;
  lat?: number;
  lng?: number;
  startNode?: boolean;
}
