/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DepotSummaryProjectionType = typeof DepotSummaryProjectionType[keyof typeof DepotSummaryProjectionType];


export const DepotSummaryProjectionType = {
  BGD: 'BGD',
  SOC: 'SOC',
} as const;
