/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DepotResultType = typeof DepotResultType[keyof typeof DepotResultType];


export const DepotResultType = {
  BGD: 'BGD',
  SOC: 'SOC',
} as const;
