/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DepotId } from './depotId';
import type { DepotResultType } from './depotResultType';

export interface DepotResult {
  id?: DepotId;
  name?: string;
  type?: DepotResultType;
  lat?: number;
  lng?: number;
  isStartNode?: boolean;
}
