/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ErrorResponseErrors } from './errorResponseErrors';

export interface ErrorResponse {
  timestamp?: string;
  path?: string;
  status?: number;
  message?: string;
  errors?: ErrorResponseErrors;
  errorCode?: string;
}
