/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SearchPageable } from './searchPageable';

export type GetAllUserProfilesParams = {
pageable: SearchPageable;
};
