/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetAllPermissionsParams = {
filter?: string;
sorts?: string[];
page?: number;
size?: number;
};
