/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { InitiateMfaSetupMethod } from './initiateMfaSetupMethod';

export type InitiateMfaSetupParams = {
method: InitiateMfaSetupMethod;
};
