/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type MfaChallengeResultMethod = typeof MfaChallengeResultMethod[keyof typeof MfaChallengeResultMethod];


export const MfaChallengeResultMethod = {
  TOTP: 'TOTP',
  EMAIL: 'EMAIL',
  WEBAUTHN: 'WEBAUTHN',
} as const;
