/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type MfaChallengeCommandMethod = typeof MfaChallengeCommandMethod[keyof typeof MfaChallengeCommandMethod];


export const MfaChallengeCommandMethod = {
  TOTP: 'TOTP',
  EMAIL: 'EMAIL',
  WEBAUTHN: 'WEBAUTHN',
} as const;
