/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MfaChallengeResultMethod } from './mfaChallengeResultMethod';

export interface MfaChallengeResult {
  method?: MfaChallengeResultMethod;
  challengeId?: string;
  status?: string;
  publicOptionsJson?: string;
  maskedTarget?: string;
}
