/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MfaChallengeCommandMethod } from './mfaChallengeCommandMethod';

export interface MfaChallengeCommand {
  method?: MfaChallengeCommandMethod;
  verificationToken?: string;
}
