/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderDetailProjectionStatus } from './orderDetailProjectionStatus';
import type { OrderDetailProjectionType } from './orderDetailProjectionType';

export interface OrderDetailProjection {
  id?: string;
  type?: OrderDetailProjectionType;
  dimensions?: string;
  description?: string;
  status?: OrderDetailProjectionStatus;
  trackingCode?: string;
  customerId?: string;
  senderId?: string;
  senderName?: string;
  senderPhone?: string;
  senderAddress?: string;
  senderWardId?: string;
  senderProvinceId?: string;
  recipientName?: string;
  recipientPhone?: string;
  recipientAddress?: string;
  recipientWardId?: string;
  recipientProvinceId?: string;
  weight?: number;
  valueDeclared?: number;
  fragile?: boolean;
  requiresSignature?: boolean;
  shippingFee?: number;
  insuranceFee?: number;
  totalAmount?: number;
  assignedDriverId?: string;
  depotId?: string;
  estimatedDeliveryDate?: string;
  actualDeliveryDate?: string;
  notes?: string;
  rejectionReason?: string;
  createdAt?: string;
  updatedAt?: string;
}
