/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OrderSummaryProjectionType = typeof OrderSummaryProjectionType[keyof typeof OrderSummaryProjectionType];


export const OrderSummaryProjectionType = {
  EXPRESS: 'EXPRESS',
  STANDARD: 'STANDARD',
  ECONOMY: 'ECONOMY',
} as const;
