/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OrderResultType = typeof OrderResultType[keyof typeof OrderResultType];


export const OrderResultType = {
  EXPRESS: 'EXPRESS',
  STANDARD: 'STANDARD',
  ECONOMY: 'ECONOMY',
} as const;
