/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderSummaryProjectionStatus } from './orderSummaryProjectionStatus';
import type { OrderSummaryProjectionType } from './orderSummaryProjectionType';

export interface OrderSummaryProjection {
  id?: string;
  type?: OrderSummaryProjectionType;
  status?: OrderSummaryProjectionStatus;
  trackingCode?: string;
  customerId?: string;
  senderName?: string;
  recipientName?: string;
  recipientAddress?: string;
  totalAmount?: number;
  createdAt?: string;
}
