/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderResultStatus } from './orderResultStatus';
import type { OrderResultType } from './orderResultType';

export interface OrderResult {
  id?: string;
  trackingCode?: string;
  type?: OrderResultType;
  status?: OrderResultStatus;
  customerId?: string;
  senderName?: string;
  recipientName?: string;
  recipientAddress?: string;
  totalAmount?: number;
  assignedDriverId?: string;
}
