/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OrderDetailProjectionType = typeof OrderDetailProjectionType[keyof typeof OrderDetailProjectionType];


export const OrderDetailProjectionType = {
  EXPRESS: 'EXPRESS',
  STANDARD: 'STANDARD',
  ECONOMY: 'ECONOMY',
} as const;
