/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WardSummaryProjection } from './wardSummaryProjection';

export interface PageResponseWardSummaryProjection {
  content?: WardSummaryProjection[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
  first?: boolean;
}
