/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderSummaryProjection } from './orderSummaryProjection';

export interface PageResponseOrderSummaryProjection {
  content?: OrderSummaryProjection[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
  first?: boolean;
}
