/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PermissionSummaryProjection } from './permissionSummaryProjection';

export interface PageResponsePermissionSummaryProjection {
  content?: PermissionSummaryProjection[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
  first?: boolean;
}
