/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProvinceSummaryProjection } from './provinceSummaryProjection';

export interface PageResponseProvinceSummaryProjection {
  content?: ProvinceSummaryProjection[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
  first?: boolean;
}
