/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PermissionSummaryProjection {
  name?: string;
  resource?: string;
  id?: string;
  description?: string;
  action?: string;
}
