/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Coordinate } from './coordinate';

export interface Polygon {
  coordinates?: Coordinate[];
}
