/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProcessVerificationQueryPurpose } from './processVerificationQueryPurpose';

export interface ProcessVerificationQuery {
  purpose?: ProcessVerificationQueryPurpose;
  recipient?: string;
  code?: string;
}
