/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProvinceResultType = typeof ProvinceResultType[keyof typeof ProvinceResultType];


export const ProvinceResultType = {
  CITY: 'CITY',
  PROVINCE: 'PROVINCE',
} as const;
