/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProvinceId } from './provinceId';
import type { ProvinceResultType } from './provinceResultType';

export interface ProvinceResult {
  id?: ProvinceId;
  code?: string;
  name?: string;
  type?: ProvinceResultType;
}
