/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RegisterCommand {
  verificationToken?: string;
  email?: string;
  fullName?: string;
  password?: string;
}
