/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RoleSummaryProjection {
  isDefault?: boolean;
  systemRole?: boolean;
  name?: string;
  id?: string;
  description?: string;
}
