/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RoleId } from './roleId';

export interface RoleResult {
  id?: RoleId;
  name?: string;
  description?: string;
  isDefault?: boolean;
  systemRole?: boolean;
}
