/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SendVerificationCodeQueryChannel = typeof SendVerificationCodeQueryChannel[keyof typeof SendVerificationCodeQueryChannel];


export const SendVerificationCodeQueryChannel = {
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
} as const;
