/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SendVerificationCodeQueryPurpose = typeof SendVerificationCodeQueryPurpose[keyof typeof SendVerificationCodeQueryPurpose];


export const SendVerificationCodeQueryPurpose = {
  PHONE_VERIFICATION: 'PHONE_VERIFICATION',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
} as const;
