/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SendVerificationCodeQueryChannel } from './sendVerificationCodeQueryChannel';
import type { SendVerificationCodeQueryPurpose } from './sendVerificationCodeQueryPurpose';

export interface SendVerificationCodeQuery {
  purpose?: SendVerificationCodeQueryPurpose;
  channel?: SendVerificationCodeQueryChannel;
  recipient?: string;
}
