/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TopUpRequestProvider } from './topUpRequestProvider';

export interface TopUpRequest {
  /** @minimum 10000 */
  amount: number;
  provider: TopUpRequestProvider;
}
