/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateContactRequest {
  name?: string;
  phoneNumber?: string;
  address?: string;
  note?: string;
}
