/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateDepotRequestType = typeof UpdateDepotRequestType[keyof typeof UpdateDepotRequestType];


export const UpdateDepotRequestType = {
  BGD: 'BGD',
  SOC: 'SOC',
} as const;
