/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateUserStatusRequestStatus } from './updateUserStatusRequestStatus';

export interface UpdateUserStatusRequest {
  status?: UpdateUserStatusRequestStatus;
}
