/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Polygon } from './polygon';
import type { UpdateWardRequestType } from './updateWardRequestType';

export interface UpdateWardRequest {
  code?: string;
  name?: string;
  provinceId?: string;
  type?: UpdateWardRequestType;
  polygon?: Polygon;
}
