/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateProvinceRequestType } from './updateProvinceRequestType';

export interface UpdateProvinceRequest {
  code?: string;
  name?: string;
  type?: UpdateProvinceRequestType;
}
