/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateUserStatusRequestStatus = typeof UpdateUserStatusRequestStatus[keyof typeof UpdateUserStatusRequestStatus];


export const UpdateUserStatusRequestStatus = {
  UNVERIFIED: 'UNVERIFIED',
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  DELETED: 'DELETED',
} as const;
