/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateDepotRequestType } from './updateDepotRequestType';

export interface UpdateDepotRequest {
  name?: string;
  type?: UpdateDepotRequestType;
  latitude?: number;
  longitude?: number;
}
