/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateProvinceRequestType = typeof UpdateProvinceRequestType[keyof typeof UpdateProvinceRequestType];


export const UpdateProvinceRequestType = {
  CITY: 'CITY',
  PROVINCE: 'PROVINCE',
} as const;
