/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateWardRequestType = typeof UpdateWardRequestType[keyof typeof UpdateWardRequestType];


export const UpdateWardRequestType = {
  WARD: 'WARD',
  COMMUNE: 'COMMUNE',
  TOWNSHIP: 'TOWNSHIP',
  TOWN: 'TOWN',
} as const;
