/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UploadPresignedUrlCommandType = typeof UploadPresignedUrlCommandType[keyof typeof UploadPresignedUrlCommandType];


export const UploadPresignedUrlCommandType = {
  AVATAR: 'AVATAR',
} as const;
