/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UploadPresignedUrlCommandType } from './uploadPresignedUrlCommandType';

export interface UploadPresignedUrlCommand {
  fileName?: string;
  contentType?: string;
  fileSize?: number;
  type?: UploadPresignedUrlCommandType;
}
