/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserSummaryProjectionUserStatus = typeof UserSummaryProjectionUserStatus[keyof typeof UserSummaryProjectionUserStatus];


export const UserSummaryProjectionUserStatus = {
  UNVERIFIED: 'UNVERIFIED',
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  DELETED: 'DELETED',
} as const;
