/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Email } from './email';
import type { PhoneNumber } from './phoneNumber';
import type { UserSummaryProjectionUserStatus } from './userSummaryProjectionUserStatus';

export interface UserSummaryProjection {
  fullname?: string;
  userStatus?: UserSummaryProjectionUserStatus;
  id?: number;
  email?: Email;
  phoneNumber?: PhoneNumber;
}
