/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserSummaryProjectionStatus } from './userSummaryProjectionStatus';

export interface UserSummaryProjection {
  id?: string;
  fullname?: string;
  roleName?: string;
  phoneNumber?: string;
  email?: string;
  status?: UserSummaryProjectionStatus;
}
