/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface VehicleSummaryProjection {
  id: string;
  type: string;
  licensePlate: string;
  maxWeight?: number;
  maxVolume?: number;
  shipperId?: string;
}
