/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type VehicleResultType = typeof VehicleResultType[keyof typeof VehicleResultType];


export const VehicleResultType = {
  MOTORBIKE: 'MOTORBIKE',
  VAN: 'VAN',
  TRUCK: 'TRUCK',
} as const;
