/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserId } from './userId';
import type { VehicleId } from './vehicleId';
import type { VehicleResultType } from './vehicleResultType';

export interface VehicleResult {
  id?: VehicleId;
  licensePlate?: string;
  type?: VehicleResultType;
  maxWeight?: number;
  maxVolume?: number;
  shipperId?: UserId;
}
