/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type VehicleRequestType = typeof VehicleRequestType[keyof typeof VehicleRequestType];


export const VehicleRequestType = {
  MOTORBIKE: 'MOTORBIKE',
  VAN: 'VAN',
  TRUCK: 'TRUCK',
} as const;
