/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WalletResultStatus } from './walletResultStatus';

export interface WalletResult {
  walletId?: string;
  balance?: number;
  currency?: string;
  formattedBalance?: string;
  status?: WalletResultStatus;
}
