/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Polygon } from './polygon';
import type { ProvinceId } from './provinceId';
import type { WardId } from './wardId';
import type { WardResultType } from './wardResultType';

export interface WardResult {
  id?: WardId;
  code?: string;
  name?: string;
  provinceId?: ProvinceId;
  type?: WardResultType;
  polygon?: Polygon;
}
