/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type WardResultType = typeof WardResultType[keyof typeof WardResultType];


export const WardResultType = {
  WARD: 'WARD',
  COMMUNE: 'COMMUNE',
  TOWNSHIP: 'TOWNSHIP',
  TOWN: 'TOWN',
} as const;
