/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WardSummaryProjectionType } from './wardSummaryProjectionType';

export interface WardSummaryProjection {
  name?: string;
  id?: string;
  type?: WardSummaryProjectionType;
  code?: string;
}
