/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type WardSummaryProjectionType = typeof WardSummaryProjectionType[keyof typeof WardSummaryProjectionType];


export const WardSummaryProjectionType = {
  WARD: 'WARD',
  COMMUNE: 'COMMUNE',
  TOWNSHIP: 'TOWNSHIP',
  TOWN: 'TOWN',
} as const;
