/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Nếu sử dụng swagger thì sẽ không được do bị chặn bởi CORS. Vui lòng click vào link kế bên để đăng nhập bằng Google.[/oauth2/authorize/google](/oauth2/authorize/google)
 * @summary Endpoint giúp đăng nhập bằng OAuth2. Hiện tại hỗ trợ Google
 */
export const redirectToProvider = (
    provider: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<void>(
      {url: `/oauth2/authorize/${provider}`, method: 'GET', signal
    },
      options);
    }
  



export const getRedirectToProviderQueryKey = (provider: string,) => {
    return [
    `/oauth2/authorize/${provider}`
    ] as const;
    }

    
export const getRedirectToProviderQueryOptions = <TData = Awaited<ReturnType<typeof redirectToProvider>>, TError = ErrorType<ErrorResponse>>(provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToProvider>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRedirectToProviderQueryKey(provider);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof redirectToProvider>>> = ({ signal }) => redirectToProvider(provider, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(provider), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof redirectToProvider>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RedirectToProviderQueryResult = NonNullable<Awaited<ReturnType<typeof redirectToProvider>>>
export type RedirectToProviderQueryError = ErrorType<ErrorResponse>


export function useRedirectToProvider<TData = Awaited<ReturnType<typeof redirectToProvider>>, TError = ErrorType<ErrorResponse>>(
 provider: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToProvider>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof redirectToProvider>>,
          TError,
          Awaited<ReturnType<typeof redirectToProvider>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRedirectToProvider<TData = Awaited<ReturnType<typeof redirectToProvider>>, TError = ErrorType<ErrorResponse>>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToProvider>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof redirectToProvider>>,
          TError,
          Awaited<ReturnType<typeof redirectToProvider>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRedirectToProvider<TData = Awaited<ReturnType<typeof redirectToProvider>>, TError = ErrorType<ErrorResponse>>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToProvider>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Endpoint giúp đăng nhập bằng OAuth2. Hiện tại hỗ trợ Google
 */

export function useRedirectToProvider<TData = Awaited<ReturnType<typeof redirectToProvider>>, TError = ErrorType<ErrorResponse>>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToProvider>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRedirectToProviderQueryOptions(provider,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




