/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Get My Profile
 */
export const GetMyProfileResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "fullName": zod.string().optional(),
  "email": zod.string().optional(),
  "phoneNumber": zod.string().optional(),
  "status": zod.string().optional(),
  "phoneVerified": zod.boolean().optional(),
  "emailVerified": zod.boolean().optional()
}).optional()
})

/**
 * @summary Update My Profile
 */
export const UpdateMyProfileBody = zod.object({
  "fullName": zod.string().optional(),
  "email": zod.string().optional()
})

export const UpdateMyProfileResponse = zod.object({
  "timestamp": zod.string().datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "fullName": zod.string().optional(),
  "email": zod.string().optional(),
  "phoneNumber": zod.string().optional(),
  "status": zod.string().optional(),
  "phoneVerified": zod.boolean().optional(),
  "emailVerified": zod.boolean().optional()
}).optional()
})

