/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Pay for an Order using Wallet
 */
export const PayOrderParams = zod.object({
  "orderId": zod.string()
})

export const PayOrderResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

