/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiResponseVoid,
  ErrorResponse
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Pay for an Order using Wallet
 */
export const payOrder = (
    orderId: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/api/v1/payments/orders/${orderId}/pay`, method: 'POST', signal
    },
      options);
    }
  


export const getPayOrderMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof payOrder>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof payOrder>>, TError,{orderId: string}, TContext> => {

const mutationKey = ['payOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof payOrder>>, {orderId: string}> = (props) => {
          const {orderId} = props ?? {};

          return  payOrder(orderId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PayOrderMutationResult = NonNullable<Awaited<ReturnType<typeof payOrder>>>
    
    export type PayOrderMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Pay for an Order using Wallet
 */
export const usePayOrder = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof payOrder>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof payOrder>>,
        TError,
        {orderId: string},
        TContext
      > => {
      return useMutation(getPayOrderMutationOptions(options), queryClient);
    }
    