/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Import Wards from GeoJSON file
 */
export const ImportWardsBody = zod.object({
  "file": zod.instanceof(File)
})

export const ImportWardsResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.number().optional()
})

/**
 * @summary Import Provinces from GeoJSON file
 */
export const ImportProvincesBody = zod.object({
  "file": zod.instanceof(File)
})

export const ImportProvincesResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.number().optional()
})

