/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiResponseInteger,
  ErrorResponse,
  ImportProvincesBody,
  ImportWardsBody
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Import Wards from GeoJSON file
 */
export const importWards = (
    importWardsBody: BodyType<ImportWardsBody>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, importWardsBody.file);

      return axiosInstanceFn<ApiResponseInteger>(
      {url: `/api/v1/admin/areas/wards/import`, method: 'POST',
       data: formData, signal
    },
      options);
    }
  


export const getImportWardsMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importWards>>, TError,{data: BodyType<ImportWardsBody>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof importWards>>, TError,{data: BodyType<ImportWardsBody>}, TContext> => {

const mutationKey = ['importWards'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importWards>>, {data: BodyType<ImportWardsBody>}> = (props) => {
          const {data} = props ?? {};

          return  importWards(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ImportWardsMutationResult = NonNullable<Awaited<ReturnType<typeof importWards>>>
    export type ImportWardsMutationBody = BodyType<ImportWardsBody>
    export type ImportWardsMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Import Wards from GeoJSON file
 */
export const useImportWards = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importWards>>, TError,{data: BodyType<ImportWardsBody>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importWards>>,
        TError,
        {data: BodyType<ImportWardsBody>},
        TContext
      > => {
      return useMutation(getImportWardsMutationOptions(options), queryClient);
    }
    /**
 * @summary Import Provinces from GeoJSON file
 */
export const importProvinces = (
    importProvincesBody: BodyType<ImportProvincesBody>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, importProvincesBody.file);

      return axiosInstanceFn<ApiResponseInteger>(
      {url: `/api/v1/admin/areas/provinces/import`, method: 'POST',
       data: formData, signal
    },
      options);
    }
  


export const getImportProvincesMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importProvinces>>, TError,{data: BodyType<ImportProvincesBody>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof importProvinces>>, TError,{data: BodyType<ImportProvincesBody>}, TContext> => {

const mutationKey = ['importProvinces'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importProvinces>>, {data: BodyType<ImportProvincesBody>}> = (props) => {
          const {data} = props ?? {};

          return  importProvinces(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ImportProvincesMutationResult = NonNullable<Awaited<ReturnType<typeof importProvinces>>>
    export type ImportProvincesMutationBody = BodyType<ImportProvincesBody>
    export type ImportProvincesMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Import Provinces from GeoJSON file
 */
export const useImportProvinces = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importProvinces>>, TError,{data: BodyType<ImportProvincesBody>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importProvinces>>,
        TError,
        {data: BodyType<ImportProvincesBody>},
        TContext
      > => {
      return useMutation(getImportProvincesMutationOptions(options), queryClient);
    }
    