/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageResponseWardSummaryProjection,
  ApiResponseVoid,
  ApiResponseWardResult,
  CreateWardCommand,
  ErrorResponse,
  GetAllWardsParams,
  UpdateWardRequest
} from '../../types';

import { axiosInstanceFn } from '../../../axiosConfig';
import type { ErrorType , BodyType } from '../../../axiosConfig';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Update an existing Ward (Cấp Xã)
 */
export const updateWard = (
    id: string,
    updateWardRequest: BodyType<UpdateWardRequest>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseWardResult>(
      {url: `/api/v1/admin/wards/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateWardRequest, signal
    },
      options);
    }
  


export const getUpdateWardMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWard>>, TError,{id: string;data: BodyType<UpdateWardRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof updateWard>>, TError,{id: string;data: BodyType<UpdateWardRequest>}, TContext> => {

const mutationKey = ['updateWard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWard>>, {id: string;data: BodyType<UpdateWardRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateWard(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateWardMutationResult = NonNullable<Awaited<ReturnType<typeof updateWard>>>
    export type UpdateWardMutationBody = BodyType<UpdateWardRequest>
    export type UpdateWardMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update an existing Ward (Cấp Xã)
 */
export const useUpdateWard = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWard>>, TError,{id: string;data: BodyType<UpdateWardRequest>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateWard>>,
        TError,
        {id: string;data: BodyType<UpdateWardRequest>},
        TContext
      > => {
      return useMutation(getUpdateWardMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete an existing Ward (Cấp Xã)
 */
export const deleteWard = (
    id: string,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseVoid>(
      {url: `/api/v1/admin/wards/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteWardMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWard>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWard>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteWard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWard>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteWard(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWardMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWard>>>
    
    export type DeleteWardMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete an existing Ward (Cấp Xã)
 */
export const useDeleteWard = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWard>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWard>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteWardMutationOptions(options), queryClient);
    }
    /**
 * Hỗ trợ phân trang, sắp xếp và filter RSQL. Ví dụ: code==XA;name==*Hội*
 * @summary Get list of Wards with pagination and filtering
 */
export const getAllWards = (
    params?: GetAllWardsParams,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponsePageResponseWardSummaryProjection>(
      {url: `/api/v1/admin/wards`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllWardsQueryKey = (params?: GetAllWardsParams,) => {
    return [
    `/api/v1/admin/wards`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllWardsQueryOptions = <TData = Awaited<ReturnType<typeof getAllWards>>, TError = ErrorType<ErrorResponse>>(params?: GetAllWardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWards>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllWardsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllWards>>> = ({ signal }) => getAllWards(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllWards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllWardsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllWards>>>
export type GetAllWardsQueryError = ErrorType<ErrorResponse>


export function useGetAllWards<TData = Awaited<ReturnType<typeof getAllWards>>, TError = ErrorType<ErrorResponse>>(
 params: undefined |  GetAllWardsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWards>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllWards>>,
          TError,
          Awaited<ReturnType<typeof getAllWards>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllWards<TData = Awaited<ReturnType<typeof getAllWards>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllWardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWards>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllWards>>,
          TError,
          Awaited<ReturnType<typeof getAllWards>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllWards<TData = Awaited<ReturnType<typeof getAllWards>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllWardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWards>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get list of Wards with pagination and filtering
 */

export function useGetAllWards<TData = Awaited<ReturnType<typeof getAllWards>>, TError = ErrorType<ErrorResponse>>(
 params?: GetAllWardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWards>>, TError, TData>>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllWardsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new Ward (Cấp Xã)
 */
export const createWard = (
    createWardCommand: BodyType<CreateWardCommand>,
 options?: SecondParameter<typeof axiosInstanceFn>,signal?: AbortSignal
) => {
      
      
      return axiosInstanceFn<ApiResponseWardResult>(
      {url: `/api/v1/admin/wards`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWardCommand, signal
    },
      options);
    }
  


export const getCreateWardMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWard>>, TError,{data: BodyType<CreateWardCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
): UseMutationOptions<Awaited<ReturnType<typeof createWard>>, TError,{data: BodyType<CreateWardCommand>}, TContext> => {

const mutationKey = ['createWard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWard>>, {data: BodyType<CreateWardCommand>}> = (props) => {
          const {data} = props ?? {};

          return  createWard(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWardMutationResult = NonNullable<Awaited<ReturnType<typeof createWard>>>
    export type CreateWardMutationBody = BodyType<CreateWardCommand>
    export type CreateWardMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create a new Ward (Cấp Xã)
 */
export const useCreateWard = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWard>>, TError,{data: BodyType<CreateWardCommand>}, TContext>, request?: SecondParameter<typeof axiosInstanceFn>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createWard>>,
        TError,
        {data: BodyType<CreateWardCommand>},
        TContext
      > => {
      return useMutation(getCreateWardMutationOptions(options), queryClient);
    }
    