/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Update an existing Ward (Cấp Xã)
 */
export const UpdateWardParams = zod.object({
  "id": zod.string()
})

export const UpdateWardBody = zod.object({
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "provinceId": zod.string().optional(),
  "type": zod.enum(['WARD', 'COMMUNE', 'TOWNSHIP', 'TOWN']).optional(),
  "polygon": zod.object({
  "coordinates": zod.array(zod.object({
  "latitude": zod.number().optional(),
  "longitude": zod.number().optional()
})).optional()
}).optional()
})

export const UpdateWardResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "provinceId": zod.object({
  "value": zod.string().optional()
}).optional(),
  "type": zod.enum(['WARD', 'COMMUNE', 'TOWNSHIP', 'TOWN']).optional(),
  "polygon": zod.object({
  "coordinates": zod.array(zod.object({
  "latitude": zod.number().optional(),
  "longitude": zod.number().optional()
})).optional()
}).optional()
}).optional()
})

/**
 * @summary Delete an existing Ward (Cấp Xã)
 */
export const DeleteWardParams = zod.object({
  "id": zod.string()
})

export const DeleteWardResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.unknown().optional()
})

/**
 * Hỗ trợ phân trang, sắp xếp và filter RSQL. Ví dụ: code==XA;name==*Hội*
 * @summary Get list of Wards with pagination and filtering
 */
export const GetAllWardsQueryParams = zod.object({
  "filter": zod.string().optional(),
  "sorts": zod.array(zod.string()).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional()
})

export const GetAllWardsResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "content": zod.array(zod.object({
  "name": zod.string().optional(),
  "id": zod.string().optional(),
  "type": zod.enum(['WARD', 'COMMUNE', 'TOWNSHIP', 'TOWN']).optional(),
  "code": zod.string().optional()
})).optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional(),
  "totalElements": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "last": zod.boolean().optional(),
  "first": zod.boolean().optional()
}).optional()
})

/**
 * @summary Create a new Ward (Cấp Xã)
 */
export const CreateWardBody = zod.object({
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "provinceId": zod.object({
  "value": zod.string().optional()
}).optional(),
  "type": zod.enum(['WARD', 'COMMUNE', 'TOWNSHIP', 'TOWN']).optional(),
  "polygon": zod.object({
  "coordinates": zod.array(zod.object({
  "latitude": zod.number().optional(),
  "longitude": zod.number().optional()
})).optional()
}).optional()
})

export const CreateWardResponse = zod.object({
  "timestamp": zod.iso.datetime({}).optional(),
  "status": zod.number().optional(),
  "message": zod.string().optional(),
  "data": zod.object({
  "id": zod.object({
  "value": zod.string().optional()
}).optional(),
  "code": zod.string().optional(),
  "name": zod.string().optional(),
  "provinceId": zod.object({
  "value": zod.string().optional()
}).optional(),
  "type": zod.enum(['WARD', 'COMMUNE', 'TOWNSHIP', 'TOWN']).optional(),
  "polygon": zod.object({
  "coordinates": zod.array(zod.object({
  "latitude": zod.number().optional(),
  "longitude": zod.number().optional()
})).optional()
}).optional()
}).optional()
})

