/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticatedRoute'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Oauth2CallbackRouteImport } from './routes/oauth2/callback'
import { Route as AuthenticatedRouteMultiFactorSetRouteImport } from './routes/_authenticatedRoute/multi-factor-set'
import { Route as AuthenticatedRouteMeRouteImport } from './routes/_authenticatedRoute/me'
import { Route as AuthenticatedRouteDashboardRouteImport } from './routes/_authenticatedRoute/dashboard'
import { Route as AuthenticatedRouteContactListRouteImport } from './routes/_authenticatedRoute/contact-list'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRecoveryRouteImport } from './routes/(auth)/recovery'
import { Route as authMultiFactor0RouteImport } from './routes/(auth)/multi-factor-0'
import { Route as authMultiFactorRouteImport } from './routes/(auth)/multi-factor'
import { Route as AuthenticatedRouteUsersIndexRouteImport } from './routes/_authenticatedRoute/users/index'
import { Route as AuthenticatedRouteRolesIndexRouteImport } from './routes/_authenticatedRoute/roles/index'
import { Route as AuthenticatedRouteDepotIndexRouteImport } from './routes/_authenticatedRoute/depot/index'
import { Route as AuthenticatedRouteAreaIndexRouteImport } from './routes/_authenticatedRoute/area/index'
import { Route as AuthenticatedRouteUsersUserIdRouteImport } from './routes/_authenticatedRoute/users/$userId'
import { Route as AuthenticatedRouteRolesRoleIdRouteImport } from './routes/_authenticatedRoute/roles/$roleId'
import { Route as AuthenticatedRouteDepotDepotIdRouteImport } from './routes/_authenticatedRoute/depot/$depotId'
import { Route as AuthenticatedRouteAreaProvinceIdRouteImport } from './routes/_authenticatedRoute/area/$provinceId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticatedRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2CallbackRoute = Oauth2CallbackRouteImport.update({
  id: '/oauth2/callback',
  path: '/oauth2/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteMultiFactorSetRoute =
  AuthenticatedRouteMultiFactorSetRouteImport.update({
    id: '/multi-factor-set',
    path: '/multi-factor-set',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRouteMeRoute = AuthenticatedRouteMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRouteDashboardRoute =
  AuthenticatedRouteDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRouteContactListRoute =
  AuthenticatedRouteContactListRouteImport.update({
    id: '/contact-list',
    path: '/contact-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRecoveryRoute = authRecoveryRouteImport.update({
  id: '/(auth)/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const authMultiFactor0Route = authMultiFactor0RouteImport.update({
  id: '/(auth)/multi-factor-0',
  path: '/multi-factor-0',
  getParentRoute: () => rootRouteImport,
} as any)
const authMultiFactorRoute = authMultiFactorRouteImport.update({
  id: '/(auth)/multi-factor',
  path: '/multi-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteUsersIndexRoute =
  AuthenticatedRouteUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRouteRolesIndexRoute =
  AuthenticatedRouteRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRouteDepotIndexRoute =
  AuthenticatedRouteDepotIndexRouteImport.update({
    id: '/depot/',
    path: '/depot/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRouteAreaIndexRoute =
  AuthenticatedRouteAreaIndexRouteImport.update({
    id: '/area/',
    path: '/area/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRouteUsersUserIdRoute =
  AuthenticatedRouteUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRouteRolesRoleIdRoute =
  AuthenticatedRouteRolesRoleIdRouteImport.update({
    id: '/roles/$roleId',
    path: '/roles/$roleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRouteDepotDepotIdRoute =
  AuthenticatedRouteDepotDepotIdRouteImport.update({
    id: '/depot/$depotId',
    path: '/depot/$depotId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRouteAreaProvinceIdRoute =
  AuthenticatedRouteAreaProvinceIdRouteImport.update({
    id: '/area/$provinceId',
    path: '/area/$provinceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/multi-factor': typeof authMultiFactorRoute
  '/multi-factor-0': typeof authMultiFactor0Route
  '/recovery': typeof authRecoveryRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/contact-list': typeof AuthenticatedRouteContactListRoute
  '/dashboard': typeof AuthenticatedRouteDashboardRoute
  '/me': typeof AuthenticatedRouteMeRoute
  '/multi-factor-set': typeof AuthenticatedRouteMultiFactorSetRoute
  '/oauth2/callback': typeof Oauth2CallbackRoute
  '/area/$provinceId': typeof AuthenticatedRouteAreaProvinceIdRoute
  '/depot/$depotId': typeof AuthenticatedRouteDepotDepotIdRoute
  '/roles/$roleId': typeof AuthenticatedRouteRolesRoleIdRoute
  '/users/$userId': typeof AuthenticatedRouteUsersUserIdRoute
  '/area/': typeof AuthenticatedRouteAreaIndexRoute
  '/depot/': typeof AuthenticatedRouteDepotIndexRoute
  '/roles/': typeof AuthenticatedRouteRolesIndexRoute
  '/users/': typeof AuthenticatedRouteUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/multi-factor': typeof authMultiFactorRoute
  '/multi-factor-0': typeof authMultiFactor0Route
  '/recovery': typeof authRecoveryRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/contact-list': typeof AuthenticatedRouteContactListRoute
  '/dashboard': typeof AuthenticatedRouteDashboardRoute
  '/me': typeof AuthenticatedRouteMeRoute
  '/multi-factor-set': typeof AuthenticatedRouteMultiFactorSetRoute
  '/oauth2/callback': typeof Oauth2CallbackRoute
  '/area/$provinceId': typeof AuthenticatedRouteAreaProvinceIdRoute
  '/depot/$depotId': typeof AuthenticatedRouteDepotDepotIdRoute
  '/roles/$roleId': typeof AuthenticatedRouteRolesRoleIdRoute
  '/users/$userId': typeof AuthenticatedRouteUsersUserIdRoute
  '/area': typeof AuthenticatedRouteAreaIndexRoute
  '/depot': typeof AuthenticatedRouteDepotIndexRoute
  '/roles': typeof AuthenticatedRouteRolesIndexRoute
  '/users': typeof AuthenticatedRouteUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticatedRoute': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/multi-factor': typeof authMultiFactorRoute
  '/(auth)/multi-factor-0': typeof authMultiFactor0Route
  '/(auth)/recovery': typeof authRecoveryRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/_authenticatedRoute/contact-list': typeof AuthenticatedRouteContactListRoute
  '/_authenticatedRoute/dashboard': typeof AuthenticatedRouteDashboardRoute
  '/_authenticatedRoute/me': typeof AuthenticatedRouteMeRoute
  '/_authenticatedRoute/multi-factor-set': typeof AuthenticatedRouteMultiFactorSetRoute
  '/oauth2/callback': typeof Oauth2CallbackRoute
  '/_authenticatedRoute/area/$provinceId': typeof AuthenticatedRouteAreaProvinceIdRoute
  '/_authenticatedRoute/depot/$depotId': typeof AuthenticatedRouteDepotDepotIdRoute
  '/_authenticatedRoute/roles/$roleId': typeof AuthenticatedRouteRolesRoleIdRoute
  '/_authenticatedRoute/users/$userId': typeof AuthenticatedRouteUsersUserIdRoute
  '/_authenticatedRoute/area/': typeof AuthenticatedRouteAreaIndexRoute
  '/_authenticatedRoute/depot/': typeof AuthenticatedRouteDepotIndexRoute
  '/_authenticatedRoute/roles/': typeof AuthenticatedRouteRolesIndexRoute
  '/_authenticatedRoute/users/': typeof AuthenticatedRouteUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/multi-factor'
    | '/multi-factor-0'
    | '/recovery'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/contact-list'
    | '/dashboard'
    | '/me'
    | '/multi-factor-set'
    | '/oauth2/callback'
    | '/area/$provinceId'
    | '/depot/$depotId'
    | '/roles/$roleId'
    | '/users/$userId'
    | '/area/'
    | '/depot/'
    | '/roles/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/multi-factor'
    | '/multi-factor-0'
    | '/recovery'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/contact-list'
    | '/dashboard'
    | '/me'
    | '/multi-factor-set'
    | '/oauth2/callback'
    | '/area/$provinceId'
    | '/depot/$depotId'
    | '/roles/$roleId'
    | '/users/$userId'
    | '/area'
    | '/depot'
    | '/roles'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticatedRoute'
    | '/(auth)/multi-factor'
    | '/(auth)/multi-factor-0'
    | '/(auth)/recovery'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/_authenticatedRoute/contact-list'
    | '/_authenticatedRoute/dashboard'
    | '/_authenticatedRoute/me'
    | '/_authenticatedRoute/multi-factor-set'
    | '/oauth2/callback'
    | '/_authenticatedRoute/area/$provinceId'
    | '/_authenticatedRoute/depot/$depotId'
    | '/_authenticatedRoute/roles/$roleId'
    | '/_authenticatedRoute/users/$userId'
    | '/_authenticatedRoute/area/'
    | '/_authenticatedRoute/depot/'
    | '/_authenticatedRoute/roles/'
    | '/_authenticatedRoute/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authMultiFactorRoute: typeof authMultiFactorRoute
  authMultiFactor0Route: typeof authMultiFactor0Route
  authRecoveryRoute: typeof authRecoveryRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  Oauth2CallbackRoute: typeof Oauth2CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticatedRoute': {
      id: '/_authenticatedRoute'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/callback': {
      id: '/oauth2/callback'
      path: '/oauth2/callback'
      fullPath: '/oauth2/callback'
      preLoaderRoute: typeof Oauth2CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticatedRoute/multi-factor-set': {
      id: '/_authenticatedRoute/multi-factor-set'
      path: '/multi-factor-set'
      fullPath: '/multi-factor-set'
      preLoaderRoute: typeof AuthenticatedRouteMultiFactorSetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticatedRoute/me': {
      id: '/_authenticatedRoute/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedRouteMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticatedRoute/dashboard': {
      id: '/_authenticatedRoute/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedRouteDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticatedRoute/contact-list': {
      id: '/_authenticatedRoute/contact-list'
      path: '/contact-list'
      fullPath: '/contact-list'
      preLoaderRoute: typeof AuthenticatedRouteContactListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/recovery': {
      id: '/(auth)/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof authRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/multi-factor-0': {
      id: '/(auth)/multi-factor-0'
      path: '/multi-factor-0'
      fullPath: '/multi-factor-0'
      preLoaderRoute: typeof authMultiFactor0RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/multi-factor': {
      id: '/(auth)/multi-factor'
      path: '/multi-factor'
      fullPath: '/multi-factor'
      preLoaderRoute: typeof authMultiFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticatedRoute/users/': {
      id: '/_authenticatedRoute/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedRouteUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticatedRoute/roles/': {
      id: '/_authenticatedRoute/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRouteRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticatedRoute/depot/': {
      id: '/_authenticatedRoute/depot/'
      path: '/depot'
      fullPath: '/depot/'
      preLoaderRoute: typeof AuthenticatedRouteDepotIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticatedRoute/area/': {
      id: '/_authenticatedRoute/area/'
      path: '/area'
      fullPath: '/area/'
      preLoaderRoute: typeof AuthenticatedRouteAreaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticatedRoute/users/$userId': {
      id: '/_authenticatedRoute/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedRouteUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticatedRoute/roles/$roleId': {
      id: '/_authenticatedRoute/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof AuthenticatedRouteRolesRoleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticatedRoute/depot/$depotId': {
      id: '/_authenticatedRoute/depot/$depotId'
      path: '/depot/$depotId'
      fullPath: '/depot/$depotId'
      preLoaderRoute: typeof AuthenticatedRouteDepotDepotIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticatedRoute/area/$provinceId': {
      id: '/_authenticatedRoute/area/$provinceId'
      path: '/area/$provinceId'
      fullPath: '/area/$provinceId'
      preLoaderRoute: typeof AuthenticatedRouteAreaProvinceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRouteContactListRoute: typeof AuthenticatedRouteContactListRoute
  AuthenticatedRouteDashboardRoute: typeof AuthenticatedRouteDashboardRoute
  AuthenticatedRouteMeRoute: typeof AuthenticatedRouteMeRoute
  AuthenticatedRouteMultiFactorSetRoute: typeof AuthenticatedRouteMultiFactorSetRoute
  AuthenticatedRouteAreaProvinceIdRoute: typeof AuthenticatedRouteAreaProvinceIdRoute
  AuthenticatedRouteDepotDepotIdRoute: typeof AuthenticatedRouteDepotDepotIdRoute
  AuthenticatedRouteRolesRoleIdRoute: typeof AuthenticatedRouteRolesRoleIdRoute
  AuthenticatedRouteUsersUserIdRoute: typeof AuthenticatedRouteUsersUserIdRoute
  AuthenticatedRouteAreaIndexRoute: typeof AuthenticatedRouteAreaIndexRoute
  AuthenticatedRouteDepotIndexRoute: typeof AuthenticatedRouteDepotIndexRoute
  AuthenticatedRouteRolesIndexRoute: typeof AuthenticatedRouteRolesIndexRoute
  AuthenticatedRouteUsersIndexRoute: typeof AuthenticatedRouteUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRouteContactListRoute: AuthenticatedRouteContactListRoute,
  AuthenticatedRouteDashboardRoute: AuthenticatedRouteDashboardRoute,
  AuthenticatedRouteMeRoute: AuthenticatedRouteMeRoute,
  AuthenticatedRouteMultiFactorSetRoute: AuthenticatedRouteMultiFactorSetRoute,
  AuthenticatedRouteAreaProvinceIdRoute: AuthenticatedRouteAreaProvinceIdRoute,
  AuthenticatedRouteDepotDepotIdRoute: AuthenticatedRouteDepotDepotIdRoute,
  AuthenticatedRouteRolesRoleIdRoute: AuthenticatedRouteRolesRoleIdRoute,
  AuthenticatedRouteUsersUserIdRoute: AuthenticatedRouteUsersUserIdRoute,
  AuthenticatedRouteAreaIndexRoute: AuthenticatedRouteAreaIndexRoute,
  AuthenticatedRouteDepotIndexRoute: AuthenticatedRouteDepotIndexRoute,
  AuthenticatedRouteRolesIndexRoute: AuthenticatedRouteRolesIndexRoute,
  AuthenticatedRouteUsersIndexRoute: AuthenticatedRouteUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authMultiFactorRoute: authMultiFactorRoute,
  authMultiFactor0Route: authMultiFactor0Route,
  authRecoveryRoute: authRecoveryRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  Oauth2CallbackRoute: Oauth2CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
